//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

@kotlin.jvm.JvmSynthetic
public inline fun durationRules(block: io.envoyproxy.pgv.validate.DurationRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.DurationRules =
  io.envoyproxy.pgv.validate.DurationRulesKt.Dsl._create(io.envoyproxy.pgv.validate.Validate.DurationRules.newBuilder()).apply { block() }._build()
public object DurationRulesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.envoyproxy.pgv.validate.Validate.DurationRules.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.envoyproxy.pgv.validate.Validate.DurationRules.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.envoyproxy.pgv.validate.Validate.DurationRules = _builder.build()

    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     */
    public var required: kotlin.Boolean
      @JvmName("getRequired")
      get() = _builder.getRequired()
      @JvmName("setRequired")
      set(value) {
        _builder.setRequired(value)
      }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     */
    public fun clearRequired() {
      _builder.clearRequired()
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     * @return Whether the required field is set.
     */
    public fun hasRequired(): kotlin.Boolean {
      return _builder.hasRequired()
    }

    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional .google.protobuf.Duration const = 2;</code>
     */
    public var const: com.google.protobuf.Duration
      @JvmName("getConst")
      get() = _builder.getConst()
      @JvmName("setConst")
      set(value) {
        _builder.setConst(value)
      }
    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional .google.protobuf.Duration const = 2;</code>
     */
    public fun clearConst() {
      _builder.clearConst()
    }
    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional .google.protobuf.Duration const = 2;</code>
     * @return Whether the const field is set.
     */
    public fun hasConst(): kotlin.Boolean {
      return _builder.hasConst()
    }

    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration lt = 3;</code>
     */
    public var lt: com.google.protobuf.Duration
      @JvmName("getLt")
      get() = _builder.getLt()
      @JvmName("setLt")
      set(value) {
        _builder.setLt(value)
      }
    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration lt = 3;</code>
     */
    public fun clearLt() {
      _builder.clearLt()
    }
    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration lt = 3;</code>
     * @return Whether the lt field is set.
     */
    public fun hasLt(): kotlin.Boolean {
      return _builder.hasLt()
    }

    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration lte = 4;</code>
     */
    public var lte: com.google.protobuf.Duration
      @JvmName("getLte")
      get() = _builder.getLte()
      @JvmName("setLte")
      set(value) {
        _builder.setLte(value)
      }
    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration lte = 4;</code>
     */
    public fun clearLte() {
      _builder.clearLte()
    }
    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration lte = 4;</code>
     * @return Whether the lte field is set.
     */
    public fun hasLte(): kotlin.Boolean {
      return _builder.hasLte()
    }

    /**
     * <pre>
     * Gt specifies that this field must be greater than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration gt = 5;</code>
     */
    public var gt: com.google.protobuf.Duration
      @JvmName("getGt")
      get() = _builder.getGt()
      @JvmName("setGt")
      set(value) {
        _builder.setGt(value)
      }
    /**
     * <pre>
     * Gt specifies that this field must be greater than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration gt = 5;</code>
     */
    public fun clearGt() {
      _builder.clearGt()
    }
    /**
     * <pre>
     * Gt specifies that this field must be greater than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration gt = 5;</code>
     * @return Whether the gt field is set.
     */
    public fun hasGt(): kotlin.Boolean {
      return _builder.hasGt()
    }

    /**
     * <pre>
     * Gte specifies that this field must be greater than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration gte = 6;</code>
     */
    public var gte: com.google.protobuf.Duration
      @JvmName("getGte")
      get() = _builder.getGte()
      @JvmName("setGte")
      set(value) {
        _builder.setGte(value)
      }
    /**
     * <pre>
     * Gte specifies that this field must be greater than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration gte = 6;</code>
     */
    public fun clearGte() {
      _builder.clearGte()
    }
    /**
     * <pre>
     * Gte specifies that this field must be greater than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Duration gte = 6;</code>
     * @return Whether the gte field is set.
     */
    public fun hasGte(): kotlin.Boolean {
      return _builder.hasGte()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class In_Proxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     */
     public val in_: com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getInList()
      )
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     * @param value The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addIn_")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>.add(value: com.google.protobuf.Duration) {
      _builder.addIn(value)
    }/**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     * @param value The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignIn_")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>.plusAssign(value: com.google.protobuf.Duration) {
      add(value)
    }/**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     * @param values The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllIn_")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Duration>) {
      _builder.addAllIn(values)
    }/**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     * @param values The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllIn_")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Duration>) {
      addAll(values)
    }/**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     * @param index The index to set the value at.
     * @param value The in to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setIn_")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>.set(index: kotlin.Int, value: com.google.protobuf.Duration) {
      _builder.setIn(index, value)
    }/**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration in = 7;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearIn_")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, In_Proxy>.clear() {
      _builder.clearIn()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NotInProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     */
     public val notIn: com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getNotInList()
      )
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     * @param value The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNotIn")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>.add(value: com.google.protobuf.Duration) {
      _builder.addNotIn(value)
    }/**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     * @param value The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNotIn")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>.plusAssign(value: com.google.protobuf.Duration) {
      add(value)
    }/**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     * @param values The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNotIn")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Duration>) {
      _builder.addAllNotIn(values)
    }/**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     * @param values The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNotIn")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Duration>) {
      addAll(values)
    }/**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     * @param index The index to set the value at.
     * @param value The notIn to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNotIn")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>.set(index: kotlin.Int, value: com.google.protobuf.Duration) {
      _builder.setNotIn(index, value)
    }/**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated .google.protobuf.Duration not_in = 8;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNotIn")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Duration, NotInProxy>.clear() {
      _builder.clearNotIn()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun io.envoyproxy.pgv.validate.Validate.DurationRules.copy(block: io.envoyproxy.pgv.validate.DurationRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.DurationRules =
  io.envoyproxy.pgv.validate.DurationRulesKt.Dsl._create(this.toBuilder()).apply { block() }._build()
