//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

@kotlin.jvm.JvmSynthetic
public inline fun fieldRules(block: io.envoyproxy.pgv.validate.FieldRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.FieldRules =
  io.envoyproxy.pgv.validate.FieldRulesKt.Dsl._create(io.envoyproxy.pgv.validate.Validate.FieldRules.newBuilder()).apply { block() }._build()
public object FieldRulesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.envoyproxy.pgv.validate.Validate.FieldRules.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.envoyproxy.pgv.validate.Validate.FieldRules.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.envoyproxy.pgv.validate.Validate.FieldRules = _builder.build()

    /**
     * <code>optional .validate.MessageRules message = 17;</code>
     */
    public var message: io.envoyproxy.pgv.validate.Validate.MessageRules
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>optional .validate.MessageRules message = 17;</code>
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * <code>optional .validate.MessageRules message = 17;</code>
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }

    /**
     * <pre>
     * Scalar Field Types
     * </pre>
     *
     * <code>.validate.FloatRules float = 1;</code>
     */
    public var float: io.envoyproxy.pgv.validate.Validate.FloatRules
      @JvmName("getFloat")
      get() = _builder.getFloat()
      @JvmName("setFloat")
      set(value) {
        _builder.setFloat(value)
      }
    /**
     * <pre>
     * Scalar Field Types
     * </pre>
     *
     * <code>.validate.FloatRules float = 1;</code>
     */
    public fun clearFloat() {
      _builder.clearFloat()
    }
    /**
     * <pre>
     * Scalar Field Types
     * </pre>
     *
     * <code>.validate.FloatRules float = 1;</code>
     * @return Whether the float field is set.
     */
    public fun hasFloat(): kotlin.Boolean {
      return _builder.hasFloat()
    }

    /**
     * <code>.validate.DoubleRules double = 2;</code>
     */
    public var double: io.envoyproxy.pgv.validate.Validate.DoubleRules
      @JvmName("getDouble")
      get() = _builder.getDouble()
      @JvmName("setDouble")
      set(value) {
        _builder.setDouble(value)
      }
    /**
     * <code>.validate.DoubleRules double = 2;</code>
     */
    public fun clearDouble() {
      _builder.clearDouble()
    }
    /**
     * <code>.validate.DoubleRules double = 2;</code>
     * @return Whether the double field is set.
     */
    public fun hasDouble(): kotlin.Boolean {
      return _builder.hasDouble()
    }

    /**
     * <code>.validate.Int32Rules int32 = 3;</code>
     */
    public var int32: io.envoyproxy.pgv.validate.Validate.Int32Rules
      @JvmName("getInt32")
      get() = _builder.getInt32()
      @JvmName("setInt32")
      set(value) {
        _builder.setInt32(value)
      }
    /**
     * <code>.validate.Int32Rules int32 = 3;</code>
     */
    public fun clearInt32() {
      _builder.clearInt32()
    }
    /**
     * <code>.validate.Int32Rules int32 = 3;</code>
     * @return Whether the int32 field is set.
     */
    public fun hasInt32(): kotlin.Boolean {
      return _builder.hasInt32()
    }

    /**
     * <code>.validate.Int64Rules int64 = 4;</code>
     */
    public var int64: io.envoyproxy.pgv.validate.Validate.Int64Rules
      @JvmName("getInt64")
      get() = _builder.getInt64()
      @JvmName("setInt64")
      set(value) {
        _builder.setInt64(value)
      }
    /**
     * <code>.validate.Int64Rules int64 = 4;</code>
     */
    public fun clearInt64() {
      _builder.clearInt64()
    }
    /**
     * <code>.validate.Int64Rules int64 = 4;</code>
     * @return Whether the int64 field is set.
     */
    public fun hasInt64(): kotlin.Boolean {
      return _builder.hasInt64()
    }

    /**
     * <code>.validate.UInt32Rules uint32 = 5;</code>
     */
    public var uint32: io.envoyproxy.pgv.validate.Validate.UInt32Rules
      @JvmName("getUint32")
      get() = _builder.getUint32()
      @JvmName("setUint32")
      set(value) {
        _builder.setUint32(value)
      }
    /**
     * <code>.validate.UInt32Rules uint32 = 5;</code>
     */
    public fun clearUint32() {
      _builder.clearUint32()
    }
    /**
     * <code>.validate.UInt32Rules uint32 = 5;</code>
     * @return Whether the uint32 field is set.
     */
    public fun hasUint32(): kotlin.Boolean {
      return _builder.hasUint32()
    }

    /**
     * <code>.validate.UInt64Rules uint64 = 6;</code>
     */
    public var uint64: io.envoyproxy.pgv.validate.Validate.UInt64Rules
      @JvmName("getUint64")
      get() = _builder.getUint64()
      @JvmName("setUint64")
      set(value) {
        _builder.setUint64(value)
      }
    /**
     * <code>.validate.UInt64Rules uint64 = 6;</code>
     */
    public fun clearUint64() {
      _builder.clearUint64()
    }
    /**
     * <code>.validate.UInt64Rules uint64 = 6;</code>
     * @return Whether the uint64 field is set.
     */
    public fun hasUint64(): kotlin.Boolean {
      return _builder.hasUint64()
    }

    /**
     * <code>.validate.SInt32Rules sint32 = 7;</code>
     */
    public var sint32: io.envoyproxy.pgv.validate.Validate.SInt32Rules
      @JvmName("getSint32")
      get() = _builder.getSint32()
      @JvmName("setSint32")
      set(value) {
        _builder.setSint32(value)
      }
    /**
     * <code>.validate.SInt32Rules sint32 = 7;</code>
     */
    public fun clearSint32() {
      _builder.clearSint32()
    }
    /**
     * <code>.validate.SInt32Rules sint32 = 7;</code>
     * @return Whether the sint32 field is set.
     */
    public fun hasSint32(): kotlin.Boolean {
      return _builder.hasSint32()
    }

    /**
     * <code>.validate.SInt64Rules sint64 = 8;</code>
     */
    public var sint64: io.envoyproxy.pgv.validate.Validate.SInt64Rules
      @JvmName("getSint64")
      get() = _builder.getSint64()
      @JvmName("setSint64")
      set(value) {
        _builder.setSint64(value)
      }
    /**
     * <code>.validate.SInt64Rules sint64 = 8;</code>
     */
    public fun clearSint64() {
      _builder.clearSint64()
    }
    /**
     * <code>.validate.SInt64Rules sint64 = 8;</code>
     * @return Whether the sint64 field is set.
     */
    public fun hasSint64(): kotlin.Boolean {
      return _builder.hasSint64()
    }

    /**
     * <code>.validate.Fixed32Rules fixed32 = 9;</code>
     */
    public var fixed32: io.envoyproxy.pgv.validate.Validate.Fixed32Rules
      @JvmName("getFixed32")
      get() = _builder.getFixed32()
      @JvmName("setFixed32")
      set(value) {
        _builder.setFixed32(value)
      }
    /**
     * <code>.validate.Fixed32Rules fixed32 = 9;</code>
     */
    public fun clearFixed32() {
      _builder.clearFixed32()
    }
    /**
     * <code>.validate.Fixed32Rules fixed32 = 9;</code>
     * @return Whether the fixed32 field is set.
     */
    public fun hasFixed32(): kotlin.Boolean {
      return _builder.hasFixed32()
    }

    /**
     * <code>.validate.Fixed64Rules fixed64 = 10;</code>
     */
    public var fixed64: io.envoyproxy.pgv.validate.Validate.Fixed64Rules
      @JvmName("getFixed64")
      get() = _builder.getFixed64()
      @JvmName("setFixed64")
      set(value) {
        _builder.setFixed64(value)
      }
    /**
     * <code>.validate.Fixed64Rules fixed64 = 10;</code>
     */
    public fun clearFixed64() {
      _builder.clearFixed64()
    }
    /**
     * <code>.validate.Fixed64Rules fixed64 = 10;</code>
     * @return Whether the fixed64 field is set.
     */
    public fun hasFixed64(): kotlin.Boolean {
      return _builder.hasFixed64()
    }

    /**
     * <code>.validate.SFixed32Rules sfixed32 = 11;</code>
     */
    public var sfixed32: io.envoyproxy.pgv.validate.Validate.SFixed32Rules
      @JvmName("getSfixed32")
      get() = _builder.getSfixed32()
      @JvmName("setSfixed32")
      set(value) {
        _builder.setSfixed32(value)
      }
    /**
     * <code>.validate.SFixed32Rules sfixed32 = 11;</code>
     */
    public fun clearSfixed32() {
      _builder.clearSfixed32()
    }
    /**
     * <code>.validate.SFixed32Rules sfixed32 = 11;</code>
     * @return Whether the sfixed32 field is set.
     */
    public fun hasSfixed32(): kotlin.Boolean {
      return _builder.hasSfixed32()
    }

    /**
     * <code>.validate.SFixed64Rules sfixed64 = 12;</code>
     */
    public var sfixed64: io.envoyproxy.pgv.validate.Validate.SFixed64Rules
      @JvmName("getSfixed64")
      get() = _builder.getSfixed64()
      @JvmName("setSfixed64")
      set(value) {
        _builder.setSfixed64(value)
      }
    /**
     * <code>.validate.SFixed64Rules sfixed64 = 12;</code>
     */
    public fun clearSfixed64() {
      _builder.clearSfixed64()
    }
    /**
     * <code>.validate.SFixed64Rules sfixed64 = 12;</code>
     * @return Whether the sfixed64 field is set.
     */
    public fun hasSfixed64(): kotlin.Boolean {
      return _builder.hasSfixed64()
    }

    /**
     * <code>.validate.BoolRules bool = 13;</code>
     */
    public var bool: io.envoyproxy.pgv.validate.Validate.BoolRules
      @JvmName("getBool")
      get() = _builder.getBool()
      @JvmName("setBool")
      set(value) {
        _builder.setBool(value)
      }
    /**
     * <code>.validate.BoolRules bool = 13;</code>
     */
    public fun clearBool() {
      _builder.clearBool()
    }
    /**
     * <code>.validate.BoolRules bool = 13;</code>
     * @return Whether the bool field is set.
     */
    public fun hasBool(): kotlin.Boolean {
      return _builder.hasBool()
    }

    /**
     * <code>.validate.StringRules string = 14;</code>
     */
    public var string: io.envoyproxy.pgv.validate.Validate.StringRules
      @JvmName("getString")
      get() = _builder.getString()
      @JvmName("setString")
      set(value) {
        _builder.setString(value)
      }
    /**
     * <code>.validate.StringRules string = 14;</code>
     */
    public fun clearString() {
      _builder.clearString()
    }
    /**
     * <code>.validate.StringRules string = 14;</code>
     * @return Whether the string field is set.
     */
    public fun hasString(): kotlin.Boolean {
      return _builder.hasString()
    }

    /**
     * <code>.validate.BytesRules bytes = 15;</code>
     */
    public var bytes: io.envoyproxy.pgv.validate.Validate.BytesRules
      @JvmName("getBytes")
      get() = _builder.getBytes()
      @JvmName("setBytes")
      set(value) {
        _builder.setBytes(value)
      }
    /**
     * <code>.validate.BytesRules bytes = 15;</code>
     */
    public fun clearBytes() {
      _builder.clearBytes()
    }
    /**
     * <code>.validate.BytesRules bytes = 15;</code>
     * @return Whether the bytes field is set.
     */
    public fun hasBytes(): kotlin.Boolean {
      return _builder.hasBytes()
    }

    /**
     * <pre>
     * Complex Field Types
     * </pre>
     *
     * <code>.validate.EnumRules enum = 16;</code>
     */
    public var enum: io.envoyproxy.pgv.validate.Validate.EnumRules
      @JvmName("getEnum")
      get() = _builder.getEnum()
      @JvmName("setEnum")
      set(value) {
        _builder.setEnum(value)
      }
    /**
     * <pre>
     * Complex Field Types
     * </pre>
     *
     * <code>.validate.EnumRules enum = 16;</code>
     */
    public fun clearEnum() {
      _builder.clearEnum()
    }
    /**
     * <pre>
     * Complex Field Types
     * </pre>
     *
     * <code>.validate.EnumRules enum = 16;</code>
     * @return Whether the enum field is set.
     */
    public fun hasEnum(): kotlin.Boolean {
      return _builder.hasEnum()
    }

    /**
     * <code>.validate.RepeatedRules repeated = 18;</code>
     */
    public var repeated: io.envoyproxy.pgv.validate.Validate.RepeatedRules
      @JvmName("getRepeated")
      get() = _builder.getRepeated()
      @JvmName("setRepeated")
      set(value) {
        _builder.setRepeated(value)
      }
    /**
     * <code>.validate.RepeatedRules repeated = 18;</code>
     */
    public fun clearRepeated() {
      _builder.clearRepeated()
    }
    /**
     * <code>.validate.RepeatedRules repeated = 18;</code>
     * @return Whether the repeated field is set.
     */
    public fun hasRepeated(): kotlin.Boolean {
      return _builder.hasRepeated()
    }

    /**
     * <code>.validate.MapRules map = 19;</code>
     */
    public var map: io.envoyproxy.pgv.validate.Validate.MapRules
      @JvmName("getMap")
      get() = _builder.getMap()
      @JvmName("setMap")
      set(value) {
        _builder.setMap(value)
      }
    /**
     * <code>.validate.MapRules map = 19;</code>
     */
    public fun clearMap() {
      _builder.clearMap()
    }
    /**
     * <code>.validate.MapRules map = 19;</code>
     * @return Whether the map field is set.
     */
    public fun hasMap(): kotlin.Boolean {
      return _builder.hasMap()
    }

    /**
     * <pre>
     * Well-Known Field Types
     * </pre>
     *
     * <code>.validate.AnyRules any = 20;</code>
     */
    public var any: io.envoyproxy.pgv.validate.Validate.AnyRules
      @JvmName("getAny")
      get() = _builder.getAny()
      @JvmName("setAny")
      set(value) {
        _builder.setAny(value)
      }
    /**
     * <pre>
     * Well-Known Field Types
     * </pre>
     *
     * <code>.validate.AnyRules any = 20;</code>
     */
    public fun clearAny() {
      _builder.clearAny()
    }
    /**
     * <pre>
     * Well-Known Field Types
     * </pre>
     *
     * <code>.validate.AnyRules any = 20;</code>
     * @return Whether the any field is set.
     */
    public fun hasAny(): kotlin.Boolean {
      return _builder.hasAny()
    }

    /**
     * <code>.validate.DurationRules duration = 21;</code>
     */
    public var duration: io.envoyproxy.pgv.validate.Validate.DurationRules
      @JvmName("getDuration")
      get() = _builder.getDuration()
      @JvmName("setDuration")
      set(value) {
        _builder.setDuration(value)
      }
    /**
     * <code>.validate.DurationRules duration = 21;</code>
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
    /**
     * <code>.validate.DurationRules duration = 21;</code>
     * @return Whether the duration field is set.
     */
    public fun hasDuration(): kotlin.Boolean {
      return _builder.hasDuration()
    }

    /**
     * <code>.validate.TimestampRules timestamp = 22;</code>
     */
    public var timestamp: io.envoyproxy.pgv.validate.Validate.TimestampRules
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>.validate.TimestampRules timestamp = 22;</code>
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * <code>.validate.TimestampRules timestamp = 22;</code>
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }
    public val typeCase: io.envoyproxy.pgv.validate.Validate.FieldRules.TypeCase
      @JvmName("getTypeCase")
      get() = _builder.getTypeCase()

    public fun clearType() {
      _builder.clearType()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.envoyproxy.pgv.validate.Validate.FieldRules.copy(block: io.envoyproxy.pgv.validate.FieldRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.FieldRules =
  io.envoyproxy.pgv.validate.FieldRulesKt.Dsl._create(this.toBuilder()).apply { block() }._build()
