//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

@kotlin.jvm.JvmSynthetic
public inline fun stringRules(block: io.envoyproxy.pgv.validate.StringRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.StringRules =
  io.envoyproxy.pgv.validate.StringRulesKt.Dsl._create(io.envoyproxy.pgv.validate.Validate.StringRules.newBuilder()).apply { block() }._build()
public object StringRulesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.envoyproxy.pgv.validate.Validate.StringRules.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.envoyproxy.pgv.validate.Validate.StringRules.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.envoyproxy.pgv.validate.Validate.StringRules = _builder.build()

    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional string const = 1;</code>
     */
    public var const: kotlin.String
      @JvmName("getConst")
      get() = _builder.getConst()
      @JvmName("setConst")
      set(value) {
        _builder.setConst(value)
      }
    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional string const = 1;</code>
     */
    public fun clearConst() {
      _builder.clearConst()
    }
    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional string const = 1;</code>
     * @return Whether the const field is set.
     */
    public fun hasConst(): kotlin.Boolean {
      return _builder.hasConst()
    }

    /**
     * <pre>
     * Len specifies that this field must be the specified number of
     * characters (Unicode code points). Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 len = 19;</code>
     */
    public var len: kotlin.Long
      @JvmName("getLen")
      get() = _builder.getLen()
      @JvmName("setLen")
      set(value) {
        _builder.setLen(value)
      }
    /**
     * <pre>
     * Len specifies that this field must be the specified number of
     * characters (Unicode code points). Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 len = 19;</code>
     */
    public fun clearLen() {
      _builder.clearLen()
    }
    /**
     * <pre>
     * Len specifies that this field must be the specified number of
     * characters (Unicode code points). Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 len = 19;</code>
     * @return Whether the len field is set.
     */
    public fun hasLen(): kotlin.Boolean {
      return _builder.hasLen()
    }

    /**
     * <pre>
     * MinLen specifies that this field must be the specified number of
     * characters (Unicode code points) at a minimum. Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 min_len = 2;</code>
     */
    public var minLen: kotlin.Long
      @JvmName("getMinLen")
      get() = _builder.getMinLen()
      @JvmName("setMinLen")
      set(value) {
        _builder.setMinLen(value)
      }
    /**
     * <pre>
     * MinLen specifies that this field must be the specified number of
     * characters (Unicode code points) at a minimum. Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 min_len = 2;</code>
     */
    public fun clearMinLen() {
      _builder.clearMinLen()
    }
    /**
     * <pre>
     * MinLen specifies that this field must be the specified number of
     * characters (Unicode code points) at a minimum. Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 min_len = 2;</code>
     * @return Whether the minLen field is set.
     */
    public fun hasMinLen(): kotlin.Boolean {
      return _builder.hasMinLen()
    }

    /**
     * <pre>
     * MaxLen specifies that this field must be the specified number of
     * characters (Unicode code points) at a maximum. Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 max_len = 3;</code>
     */
    public var maxLen: kotlin.Long
      @JvmName("getMaxLen")
      get() = _builder.getMaxLen()
      @JvmName("setMaxLen")
      set(value) {
        _builder.setMaxLen(value)
      }
    /**
     * <pre>
     * MaxLen specifies that this field must be the specified number of
     * characters (Unicode code points) at a maximum. Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 max_len = 3;</code>
     */
    public fun clearMaxLen() {
      _builder.clearMaxLen()
    }
    /**
     * <pre>
     * MaxLen specifies that this field must be the specified number of
     * characters (Unicode code points) at a maximum. Note that the number of
     * characters may differ from the number of bytes in the string.
     * </pre>
     *
     * <code>optional uint64 max_len = 3;</code>
     * @return Whether the maxLen field is set.
     */
    public fun hasMaxLen(): kotlin.Boolean {
      return _builder.hasMaxLen()
    }

    /**
     * <pre>
     * LenBytes specifies that this field must be the specified number of bytes
     * </pre>
     *
     * <code>optional uint64 len_bytes = 20;</code>
     */
    public var lenBytes: kotlin.Long
      @JvmName("getLenBytes")
      get() = _builder.getLenBytes()
      @JvmName("setLenBytes")
      set(value) {
        _builder.setLenBytes(value)
      }
    /**
     * <pre>
     * LenBytes specifies that this field must be the specified number of bytes
     * </pre>
     *
     * <code>optional uint64 len_bytes = 20;</code>
     */
    public fun clearLenBytes() {
      _builder.clearLenBytes()
    }
    /**
     * <pre>
     * LenBytes specifies that this field must be the specified number of bytes
     * </pre>
     *
     * <code>optional uint64 len_bytes = 20;</code>
     * @return Whether the lenBytes field is set.
     */
    public fun hasLenBytes(): kotlin.Boolean {
      return _builder.hasLenBytes()
    }

    /**
     * <pre>
     * MinBytes specifies that this field must be the specified number of bytes
     * at a minimum
     * </pre>
     *
     * <code>optional uint64 min_bytes = 4;</code>
     */
    public var minBytes: kotlin.Long
      @JvmName("getMinBytes")
      get() = _builder.getMinBytes()
      @JvmName("setMinBytes")
      set(value) {
        _builder.setMinBytes(value)
      }
    /**
     * <pre>
     * MinBytes specifies that this field must be the specified number of bytes
     * at a minimum
     * </pre>
     *
     * <code>optional uint64 min_bytes = 4;</code>
     */
    public fun clearMinBytes() {
      _builder.clearMinBytes()
    }
    /**
     * <pre>
     * MinBytes specifies that this field must be the specified number of bytes
     * at a minimum
     * </pre>
     *
     * <code>optional uint64 min_bytes = 4;</code>
     * @return Whether the minBytes field is set.
     */
    public fun hasMinBytes(): kotlin.Boolean {
      return _builder.hasMinBytes()
    }

    /**
     * <pre>
     * MaxBytes specifies that this field must be the specified number of bytes
     * at a maximum
     * </pre>
     *
     * <code>optional uint64 max_bytes = 5;</code>
     */
    public var maxBytes: kotlin.Long
      @JvmName("getMaxBytes")
      get() = _builder.getMaxBytes()
      @JvmName("setMaxBytes")
      set(value) {
        _builder.setMaxBytes(value)
      }
    /**
     * <pre>
     * MaxBytes specifies that this field must be the specified number of bytes
     * at a maximum
     * </pre>
     *
     * <code>optional uint64 max_bytes = 5;</code>
     */
    public fun clearMaxBytes() {
      _builder.clearMaxBytes()
    }
    /**
     * <pre>
     * MaxBytes specifies that this field must be the specified number of bytes
     * at a maximum
     * </pre>
     *
     * <code>optional uint64 max_bytes = 5;</code>
     * @return Whether the maxBytes field is set.
     */
    public fun hasMaxBytes(): kotlin.Boolean {
      return _builder.hasMaxBytes()
    }

    /**
     * <pre>
     * Pattern specifes that this field must match against the specified
     * regular expression (RE2 syntax). The included expression should elide
     * any delimiters.
     * </pre>
     *
     * <code>optional string pattern = 6;</code>
     */
    public var pattern: kotlin.String
      @JvmName("getPattern")
      get() = _builder.getPattern()
      @JvmName("setPattern")
      set(value) {
        _builder.setPattern(value)
      }
    /**
     * <pre>
     * Pattern specifes that this field must match against the specified
     * regular expression (RE2 syntax). The included expression should elide
     * any delimiters.
     * </pre>
     *
     * <code>optional string pattern = 6;</code>
     */
    public fun clearPattern() {
      _builder.clearPattern()
    }
    /**
     * <pre>
     * Pattern specifes that this field must match against the specified
     * regular expression (RE2 syntax). The included expression should elide
     * any delimiters.
     * </pre>
     *
     * <code>optional string pattern = 6;</code>
     * @return Whether the pattern field is set.
     */
    public fun hasPattern(): kotlin.Boolean {
      return _builder.hasPattern()
    }

    /**
     * <pre>
     * Prefix specifies that this field must have the specified substring at
     * the beginning of the string.
     * </pre>
     *
     * <code>optional string prefix = 7;</code>
     */
    public var prefix: kotlin.String
      @JvmName("getPrefix")
      get() = _builder.getPrefix()
      @JvmName("setPrefix")
      set(value) {
        _builder.setPrefix(value)
      }
    /**
     * <pre>
     * Prefix specifies that this field must have the specified substring at
     * the beginning of the string.
     * </pre>
     *
     * <code>optional string prefix = 7;</code>
     */
    public fun clearPrefix() {
      _builder.clearPrefix()
    }
    /**
     * <pre>
     * Prefix specifies that this field must have the specified substring at
     * the beginning of the string.
     * </pre>
     *
     * <code>optional string prefix = 7;</code>
     * @return Whether the prefix field is set.
     */
    public fun hasPrefix(): kotlin.Boolean {
      return _builder.hasPrefix()
    }

    /**
     * <pre>
     * Suffix specifies that this field must have the specified substring at
     * the end of the string.
     * </pre>
     *
     * <code>optional string suffix = 8;</code>
     */
    public var suffix: kotlin.String
      @JvmName("getSuffix")
      get() = _builder.getSuffix()
      @JvmName("setSuffix")
      set(value) {
        _builder.setSuffix(value)
      }
    /**
     * <pre>
     * Suffix specifies that this field must have the specified substring at
     * the end of the string.
     * </pre>
     *
     * <code>optional string suffix = 8;</code>
     */
    public fun clearSuffix() {
      _builder.clearSuffix()
    }
    /**
     * <pre>
     * Suffix specifies that this field must have the specified substring at
     * the end of the string.
     * </pre>
     *
     * <code>optional string suffix = 8;</code>
     * @return Whether the suffix field is set.
     */
    public fun hasSuffix(): kotlin.Boolean {
      return _builder.hasSuffix()
    }

    /**
     * <pre>
     * Contains specifies that this field must have the specified substring
     * anywhere in the string.
     * </pre>
     *
     * <code>optional string contains = 9;</code>
     */
    public var contains: kotlin.String
      @JvmName("getContains")
      get() = _builder.getContains()
      @JvmName("setContains")
      set(value) {
        _builder.setContains(value)
      }
    /**
     * <pre>
     * Contains specifies that this field must have the specified substring
     * anywhere in the string.
     * </pre>
     *
     * <code>optional string contains = 9;</code>
     */
    public fun clearContains() {
      _builder.clearContains()
    }
    /**
     * <pre>
     * Contains specifies that this field must have the specified substring
     * anywhere in the string.
     * </pre>
     *
     * <code>optional string contains = 9;</code>
     * @return Whether the contains field is set.
     */
    public fun hasContains(): kotlin.Boolean {
      return _builder.hasContains()
    }

    /**
     * <pre>
     * NotContains specifies that this field cannot have the specified substring
     * anywhere in the string.
     * </pre>
     *
     * <code>optional string not_contains = 23;</code>
     */
    public var notContains: kotlin.String
      @JvmName("getNotContains")
      get() = _builder.getNotContains()
      @JvmName("setNotContains")
      set(value) {
        _builder.setNotContains(value)
      }
    /**
     * <pre>
     * NotContains specifies that this field cannot have the specified substring
     * anywhere in the string.
     * </pre>
     *
     * <code>optional string not_contains = 23;</code>
     */
    public fun clearNotContains() {
      _builder.clearNotContains()
    }
    /**
     * <pre>
     * NotContains specifies that this field cannot have the specified substring
     * anywhere in the string.
     * </pre>
     *
     * <code>optional string not_contains = 23;</code>
     * @return Whether the notContains field is set.
     */
    public fun hasNotContains(): kotlin.Boolean {
      return _builder.hasNotContains()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class In_Proxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     * @return A list containing the in.
     */
    public val in_: com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getInList()
      )
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     * @param value The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addIn_")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>.add(value: kotlin.String) {
      _builder.addIn(value)
    }
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     * @param value The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignIn_")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     * @param values The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllIn_")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllIn(values)
    }
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     * @param values The in to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllIn_")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     * @param index The index to set the value at.
     * @param value The in to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setIn_")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setIn(index, value)
    }/**
     * <pre>
     * In specifies that this field must be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string in = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearIn_")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, In_Proxy>.clear() {
      _builder.clearIn()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NotInProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     * @return A list containing the notIn.
     */
    public val notIn: com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getNotInList()
      )
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     * @param value The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNotIn")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>.add(value: kotlin.String) {
      _builder.addNotIn(value)
    }
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     * @param value The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNotIn")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     * @param values The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNotIn")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllNotIn(values)
    }
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     * @param values The notIn to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNotIn")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     * @param index The index to set the value at.
     * @param value The notIn to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNotIn")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setNotIn(index, value)
    }/**
     * <pre>
     * NotIn specifies that this field cannot be equal to one of the specified
     * values
     * </pre>
     *
     * <code>repeated string not_in = 11;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNotIn")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, NotInProxy>.clear() {
      _builder.clearNotIn()
    }
    /**
     * <pre>
     * Email specifies that the field must be a valid email address as
     * defined by RFC 5322
     * </pre>
     *
     * <code>bool email = 12;</code>
     */
    public var email: kotlin.Boolean
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <pre>
     * Email specifies that the field must be a valid email address as
     * defined by RFC 5322
     * </pre>
     *
     * <code>bool email = 12;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
    /**
     * <pre>
     * Email specifies that the field must be a valid email address as
     * defined by RFC 5322
     * </pre>
     *
     * <code>bool email = 12;</code>
     * @return Whether the email field is set.
     */
    public fun hasEmail(): kotlin.Boolean {
      return _builder.hasEmail()
    }

    /**
     * <pre>
     * Hostname specifies that the field must be a valid hostname as
     * defined by RFC 1034. This constraint does not support
     * internationalized domain names (IDNs).
     * </pre>
     *
     * <code>bool hostname = 13;</code>
     */
    public var hostname: kotlin.Boolean
      @JvmName("getHostname")
      get() = _builder.getHostname()
      @JvmName("setHostname")
      set(value) {
        _builder.setHostname(value)
      }
    /**
     * <pre>
     * Hostname specifies that the field must be a valid hostname as
     * defined by RFC 1034. This constraint does not support
     * internationalized domain names (IDNs).
     * </pre>
     *
     * <code>bool hostname = 13;</code>
     */
    public fun clearHostname() {
      _builder.clearHostname()
    }
    /**
     * <pre>
     * Hostname specifies that the field must be a valid hostname as
     * defined by RFC 1034. This constraint does not support
     * internationalized domain names (IDNs).
     * </pre>
     *
     * <code>bool hostname = 13;</code>
     * @return Whether the hostname field is set.
     */
    public fun hasHostname(): kotlin.Boolean {
      return _builder.hasHostname()
    }

    /**
     * <pre>
     * Ip specifies that the field must be a valid IP (v4 or v6) address.
     * Valid IPv6 addresses should not include surrounding square brackets.
     * </pre>
     *
     * <code>bool ip = 14;</code>
     */
    public var ip: kotlin.Boolean
      @JvmName("getIp")
      get() = _builder.getIp()
      @JvmName("setIp")
      set(value) {
        _builder.setIp(value)
      }
    /**
     * <pre>
     * Ip specifies that the field must be a valid IP (v4 or v6) address.
     * Valid IPv6 addresses should not include surrounding square brackets.
     * </pre>
     *
     * <code>bool ip = 14;</code>
     */
    public fun clearIp() {
      _builder.clearIp()
    }
    /**
     * <pre>
     * Ip specifies that the field must be a valid IP (v4 or v6) address.
     * Valid IPv6 addresses should not include surrounding square brackets.
     * </pre>
     *
     * <code>bool ip = 14;</code>
     * @return Whether the ip field is set.
     */
    public fun hasIp(): kotlin.Boolean {
      return _builder.hasIp()
    }

    /**
     * <pre>
     * Ipv4 specifies that the field must be a valid IPv4 address.
     * </pre>
     *
     * <code>bool ipv4 = 15;</code>
     */
    public var ipv4: kotlin.Boolean
      @JvmName("getIpv4")
      get() = _builder.getIpv4()
      @JvmName("setIpv4")
      set(value) {
        _builder.setIpv4(value)
      }
    /**
     * <pre>
     * Ipv4 specifies that the field must be a valid IPv4 address.
     * </pre>
     *
     * <code>bool ipv4 = 15;</code>
     */
    public fun clearIpv4() {
      _builder.clearIpv4()
    }
    /**
     * <pre>
     * Ipv4 specifies that the field must be a valid IPv4 address.
     * </pre>
     *
     * <code>bool ipv4 = 15;</code>
     * @return Whether the ipv4 field is set.
     */
    public fun hasIpv4(): kotlin.Boolean {
      return _builder.hasIpv4()
    }

    /**
     * <pre>
     * Ipv6 specifies that the field must be a valid IPv6 address. Valid
     * IPv6 addresses should not include surrounding square brackets.
     * </pre>
     *
     * <code>bool ipv6 = 16;</code>
     */
    public var ipv6: kotlin.Boolean
      @JvmName("getIpv6")
      get() = _builder.getIpv6()
      @JvmName("setIpv6")
      set(value) {
        _builder.setIpv6(value)
      }
    /**
     * <pre>
     * Ipv6 specifies that the field must be a valid IPv6 address. Valid
     * IPv6 addresses should not include surrounding square brackets.
     * </pre>
     *
     * <code>bool ipv6 = 16;</code>
     */
    public fun clearIpv6() {
      _builder.clearIpv6()
    }
    /**
     * <pre>
     * Ipv6 specifies that the field must be a valid IPv6 address. Valid
     * IPv6 addresses should not include surrounding square brackets.
     * </pre>
     *
     * <code>bool ipv6 = 16;</code>
     * @return Whether the ipv6 field is set.
     */
    public fun hasIpv6(): kotlin.Boolean {
      return _builder.hasIpv6()
    }

    /**
     * <pre>
     * Uri specifies that the field must be a valid, absolute URI as defined
     * by RFC 3986
     * </pre>
     *
     * <code>bool uri = 17;</code>
     */
    public var uri: kotlin.Boolean
      @JvmName("getUri")
      get() = _builder.getUri()
      @JvmName("setUri")
      set(value) {
        _builder.setUri(value)
      }
    /**
     * <pre>
     * Uri specifies that the field must be a valid, absolute URI as defined
     * by RFC 3986
     * </pre>
     *
     * <code>bool uri = 17;</code>
     */
    public fun clearUri() {
      _builder.clearUri()
    }
    /**
     * <pre>
     * Uri specifies that the field must be a valid, absolute URI as defined
     * by RFC 3986
     * </pre>
     *
     * <code>bool uri = 17;</code>
     * @return Whether the uri field is set.
     */
    public fun hasUri(): kotlin.Boolean {
      return _builder.hasUri()
    }

    /**
     * <pre>
     * UriRef specifies that the field must be a valid URI as defined by RFC
     * 3986 and may be relative or absolute.
     * </pre>
     *
     * <code>bool uri_ref = 18;</code>
     */
    public var uriRef: kotlin.Boolean
      @JvmName("getUriRef")
      get() = _builder.getUriRef()
      @JvmName("setUriRef")
      set(value) {
        _builder.setUriRef(value)
      }
    /**
     * <pre>
     * UriRef specifies that the field must be a valid URI as defined by RFC
     * 3986 and may be relative or absolute.
     * </pre>
     *
     * <code>bool uri_ref = 18;</code>
     */
    public fun clearUriRef() {
      _builder.clearUriRef()
    }
    /**
     * <pre>
     * UriRef specifies that the field must be a valid URI as defined by RFC
     * 3986 and may be relative or absolute.
     * </pre>
     *
     * <code>bool uri_ref = 18;</code>
     * @return Whether the uriRef field is set.
     */
    public fun hasUriRef(): kotlin.Boolean {
      return _builder.hasUriRef()
    }

    /**
     * <pre>
     * Address specifies that the field must be either a valid hostname as
     * defined by RFC 1034 (which does not support internationalized domain
     * names or IDNs), or it can be a valid IP (v4 or v6).
     * </pre>
     *
     * <code>bool address = 21;</code>
     */
    public var address: kotlin.Boolean
      @JvmName("getAddress")
      get() = _builder.getAddress()
      @JvmName("setAddress")
      set(value) {
        _builder.setAddress(value)
      }
    /**
     * <pre>
     * Address specifies that the field must be either a valid hostname as
     * defined by RFC 1034 (which does not support internationalized domain
     * names or IDNs), or it can be a valid IP (v4 or v6).
     * </pre>
     *
     * <code>bool address = 21;</code>
     */
    public fun clearAddress() {
      _builder.clearAddress()
    }
    /**
     * <pre>
     * Address specifies that the field must be either a valid hostname as
     * defined by RFC 1034 (which does not support internationalized domain
     * names or IDNs), or it can be a valid IP (v4 or v6).
     * </pre>
     *
     * <code>bool address = 21;</code>
     * @return Whether the address field is set.
     */
    public fun hasAddress(): kotlin.Boolean {
      return _builder.hasAddress()
    }

    /**
     * <pre>
     * Uuid specifies that the field must be a valid UUID as defined by
     * RFC 4122
     * </pre>
     *
     * <code>bool uuid = 22;</code>
     */
    public var uuid: kotlin.Boolean
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * <pre>
     * Uuid specifies that the field must be a valid UUID as defined by
     * RFC 4122
     * </pre>
     *
     * <code>bool uuid = 22;</code>
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }
    /**
     * <pre>
     * Uuid specifies that the field must be a valid UUID as defined by
     * RFC 4122
     * </pre>
     *
     * <code>bool uuid = 22;</code>
     * @return Whether the uuid field is set.
     */
    public fun hasUuid(): kotlin.Boolean {
      return _builder.hasUuid()
    }

    /**
     * <pre>
     * WellKnownRegex specifies a common well known pattern defined as a regex.
     * </pre>
     *
     * <code>.validate.KnownRegex well_known_regex = 24;</code>
     */
    public var wellKnownRegex: io.envoyproxy.pgv.validate.Validate.KnownRegex
      @JvmName("getWellKnownRegex")
      get() = _builder.getWellKnownRegex()
      @JvmName("setWellKnownRegex")
      set(value) {
        _builder.setWellKnownRegex(value)
      }
    /**
     * <pre>
     * WellKnownRegex specifies a common well known pattern defined as a regex.
     * </pre>
     *
     * <code>.validate.KnownRegex well_known_regex = 24;</code>
     */
    public fun clearWellKnownRegex() {
      _builder.clearWellKnownRegex()
    }
    /**
     * <pre>
     * WellKnownRegex specifies a common well known pattern defined as a regex.
     * </pre>
     *
     * <code>.validate.KnownRegex well_known_regex = 24;</code>
     * @return Whether the wellKnownRegex field is set.
     */
    public fun hasWellKnownRegex(): kotlin.Boolean {
      return _builder.hasWellKnownRegex()
    }

    /**
     * <pre>
     * This applies to regexes HTTP_HEADER_NAME and HTTP_HEADER_VALUE to enable
     * strict header validation.
     * By default, this is true, and HTTP header validations are RFC-compliant.
     * Setting to false will enable a looser validations that only disallows
     * &#92;r&#92;n&#92;0 characters, which can be used to bypass header matching rules.
     * </pre>
     *
     * <code>optional bool strict = 25 [default = true];</code>
     */
    public var strict: kotlin.Boolean
      @JvmName("getStrict")
      get() = _builder.getStrict()
      @JvmName("setStrict")
      set(value) {
        _builder.setStrict(value)
      }
    /**
     * <pre>
     * This applies to regexes HTTP_HEADER_NAME and HTTP_HEADER_VALUE to enable
     * strict header validation.
     * By default, this is true, and HTTP header validations are RFC-compliant.
     * Setting to false will enable a looser validations that only disallows
     * &#92;r&#92;n&#92;0 characters, which can be used to bypass header matching rules.
     * </pre>
     *
     * <code>optional bool strict = 25 [default = true];</code>
     */
    public fun clearStrict() {
      _builder.clearStrict()
    }
    /**
     * <pre>
     * This applies to regexes HTTP_HEADER_NAME and HTTP_HEADER_VALUE to enable
     * strict header validation.
     * By default, this is true, and HTTP header validations are RFC-compliant.
     * Setting to false will enable a looser validations that only disallows
     * &#92;r&#92;n&#92;0 characters, which can be used to bypass header matching rules.
     * </pre>
     *
     * <code>optional bool strict = 25 [default = true];</code>
     * @return Whether the strict field is set.
     */
    public fun hasStrict(): kotlin.Boolean {
      return _builder.hasStrict()
    }

    /**
     * <pre>
     * IgnoreEmpty specifies that the validation rules of this field should be
     * evaluated only if the field is not empty
     * </pre>
     *
     * <code>optional bool ignore_empty = 26;</code>
     */
    public var ignoreEmpty: kotlin.Boolean
      @JvmName("getIgnoreEmpty")
      get() = _builder.getIgnoreEmpty()
      @JvmName("setIgnoreEmpty")
      set(value) {
        _builder.setIgnoreEmpty(value)
      }
    /**
     * <pre>
     * IgnoreEmpty specifies that the validation rules of this field should be
     * evaluated only if the field is not empty
     * </pre>
     *
     * <code>optional bool ignore_empty = 26;</code>
     */
    public fun clearIgnoreEmpty() {
      _builder.clearIgnoreEmpty()
    }
    /**
     * <pre>
     * IgnoreEmpty specifies that the validation rules of this field should be
     * evaluated only if the field is not empty
     * </pre>
     *
     * <code>optional bool ignore_empty = 26;</code>
     * @return Whether the ignoreEmpty field is set.
     */
    public fun hasIgnoreEmpty(): kotlin.Boolean {
      return _builder.hasIgnoreEmpty()
    }
    public val wellKnownCase: io.envoyproxy.pgv.validate.Validate.StringRules.WellKnownCase
      @JvmName("getWellKnownCase")
      get() = _builder.getWellKnownCase()

    public fun clearWellKnown() {
      _builder.clearWellKnown()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.envoyproxy.pgv.validate.Validate.StringRules.copy(block: io.envoyproxy.pgv.validate.StringRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.StringRules =
  io.envoyproxy.pgv.validate.StringRulesKt.Dsl._create(this.toBuilder()).apply { block() }._build()
