//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

@kotlin.jvm.JvmSynthetic
public inline fun timestampRules(block: io.envoyproxy.pgv.validate.TimestampRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.TimestampRules =
  io.envoyproxy.pgv.validate.TimestampRulesKt.Dsl._create(io.envoyproxy.pgv.validate.Validate.TimestampRules.newBuilder()).apply { block() }._build()
public object TimestampRulesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.envoyproxy.pgv.validate.Validate.TimestampRules.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.envoyproxy.pgv.validate.Validate.TimestampRules.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.envoyproxy.pgv.validate.Validate.TimestampRules = _builder.build()

    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     */
    public var required: kotlin.Boolean
      @JvmName("getRequired")
      get() = _builder.getRequired()
      @JvmName("setRequired")
      set(value) {
        _builder.setRequired(value)
      }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     */
    public fun clearRequired() {
      _builder.clearRequired()
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     * @return Whether the required field is set.
     */
    public fun hasRequired(): kotlin.Boolean {
      return _builder.hasRequired()
    }

    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp const = 2;</code>
     */
    public var const: com.google.protobuf.Timestamp
      @JvmName("getConst")
      get() = _builder.getConst()
      @JvmName("setConst")
      set(value) {
        _builder.setConst(value)
      }
    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp const = 2;</code>
     */
    public fun clearConst() {
      _builder.clearConst()
    }
    /**
     * <pre>
     * Const specifies that this field must be exactly the specified value
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp const = 2;</code>
     * @return Whether the const field is set.
     */
    public fun hasConst(): kotlin.Boolean {
      return _builder.hasConst()
    }

    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp lt = 3;</code>
     */
    public var lt: com.google.protobuf.Timestamp
      @JvmName("getLt")
      get() = _builder.getLt()
      @JvmName("setLt")
      set(value) {
        _builder.setLt(value)
      }
    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp lt = 3;</code>
     */
    public fun clearLt() {
      _builder.clearLt()
    }
    /**
     * <pre>
     * Lt specifies that this field must be less than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp lt = 3;</code>
     * @return Whether the lt field is set.
     */
    public fun hasLt(): kotlin.Boolean {
      return _builder.hasLt()
    }

    /**
     * <pre>
     * Lte specifies that this field must be less than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp lte = 4;</code>
     */
    public var lte: com.google.protobuf.Timestamp
      @JvmName("getLte")
      get() = _builder.getLte()
      @JvmName("setLte")
      set(value) {
        _builder.setLte(value)
      }
    /**
     * <pre>
     * Lte specifies that this field must be less than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp lte = 4;</code>
     */
    public fun clearLte() {
      _builder.clearLte()
    }
    /**
     * <pre>
     * Lte specifies that this field must be less than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp lte = 4;</code>
     * @return Whether the lte field is set.
     */
    public fun hasLte(): kotlin.Boolean {
      return _builder.hasLte()
    }

    /**
     * <pre>
     * Gt specifies that this field must be greater than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp gt = 5;</code>
     */
    public var gt: com.google.protobuf.Timestamp
      @JvmName("getGt")
      get() = _builder.getGt()
      @JvmName("setGt")
      set(value) {
        _builder.setGt(value)
      }
    /**
     * <pre>
     * Gt specifies that this field must be greater than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp gt = 5;</code>
     */
    public fun clearGt() {
      _builder.clearGt()
    }
    /**
     * <pre>
     * Gt specifies that this field must be greater than the specified value,
     * exclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp gt = 5;</code>
     * @return Whether the gt field is set.
     */
    public fun hasGt(): kotlin.Boolean {
      return _builder.hasGt()
    }

    /**
     * <pre>
     * Gte specifies that this field must be greater than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp gte = 6;</code>
     */
    public var gte: com.google.protobuf.Timestamp
      @JvmName("getGte")
      get() = _builder.getGte()
      @JvmName("setGte")
      set(value) {
        _builder.setGte(value)
      }
    /**
     * <pre>
     * Gte specifies that this field must be greater than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp gte = 6;</code>
     */
    public fun clearGte() {
      _builder.clearGte()
    }
    /**
     * <pre>
     * Gte specifies that this field must be greater than the specified value,
     * inclusive
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp gte = 6;</code>
     * @return Whether the gte field is set.
     */
    public fun hasGte(): kotlin.Boolean {
      return _builder.hasGte()
    }

    /**
     * <pre>
     * LtNow specifies that this must be less than the current time. LtNow
     * can only be used with the Within rule.
     * </pre>
     *
     * <code>optional bool lt_now = 7;</code>
     */
    public var ltNow: kotlin.Boolean
      @JvmName("getLtNow")
      get() = _builder.getLtNow()
      @JvmName("setLtNow")
      set(value) {
        _builder.setLtNow(value)
      }
    /**
     * <pre>
     * LtNow specifies that this must be less than the current time. LtNow
     * can only be used with the Within rule.
     * </pre>
     *
     * <code>optional bool lt_now = 7;</code>
     */
    public fun clearLtNow() {
      _builder.clearLtNow()
    }
    /**
     * <pre>
     * LtNow specifies that this must be less than the current time. LtNow
     * can only be used with the Within rule.
     * </pre>
     *
     * <code>optional bool lt_now = 7;</code>
     * @return Whether the ltNow field is set.
     */
    public fun hasLtNow(): kotlin.Boolean {
      return _builder.hasLtNow()
    }

    /**
     * <pre>
     * GtNow specifies that this must be greater than the current time. GtNow
     * can only be used with the Within rule.
     * </pre>
     *
     * <code>optional bool gt_now = 8;</code>
     */
    public var gtNow: kotlin.Boolean
      @JvmName("getGtNow")
      get() = _builder.getGtNow()
      @JvmName("setGtNow")
      set(value) {
        _builder.setGtNow(value)
      }
    /**
     * <pre>
     * GtNow specifies that this must be greater than the current time. GtNow
     * can only be used with the Within rule.
     * </pre>
     *
     * <code>optional bool gt_now = 8;</code>
     */
    public fun clearGtNow() {
      _builder.clearGtNow()
    }
    /**
     * <pre>
     * GtNow specifies that this must be greater than the current time. GtNow
     * can only be used with the Within rule.
     * </pre>
     *
     * <code>optional bool gt_now = 8;</code>
     * @return Whether the gtNow field is set.
     */
    public fun hasGtNow(): kotlin.Boolean {
      return _builder.hasGtNow()
    }

    /**
     * <pre>
     * Within specifies that this field must be within this duration of the
     * current time. This constraint can be used alone or with the LtNow and
     * GtNow rules.
     * </pre>
     *
     * <code>optional .google.protobuf.Duration within = 9;</code>
     */
    public var within: com.google.protobuf.Duration
      @JvmName("getWithin")
      get() = _builder.getWithin()
      @JvmName("setWithin")
      set(value) {
        _builder.setWithin(value)
      }
    /**
     * <pre>
     * Within specifies that this field must be within this duration of the
     * current time. This constraint can be used alone or with the LtNow and
     * GtNow rules.
     * </pre>
     *
     * <code>optional .google.protobuf.Duration within = 9;</code>
     */
    public fun clearWithin() {
      _builder.clearWithin()
    }
    /**
     * <pre>
     * Within specifies that this field must be within this duration of the
     * current time. This constraint can be used alone or with the LtNow and
     * GtNow rules.
     * </pre>
     *
     * <code>optional .google.protobuf.Duration within = 9;</code>
     * @return Whether the within field is set.
     */
    public fun hasWithin(): kotlin.Boolean {
      return _builder.hasWithin()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.envoyproxy.pgv.validate.Validate.TimestampRules.copy(block: io.envoyproxy.pgv.validate.TimestampRulesKt.Dsl.() -> kotlin.Unit): io.envoyproxy.pgv.validate.Validate.TimestampRules =
  io.envoyproxy.pgv.validate.TimestampRulesKt.Dsl._create(this.toBuilder()).apply { block() }._build()
