//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/core.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun algebraicSubjectSet(block: com.authzed.api.v1.AlgebraicSubjectSetKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.Core.AlgebraicSubjectSet =
  com.authzed.api.v1.AlgebraicSubjectSetKt.Dsl._create(com.authzed.api.v1.Core.AlgebraicSubjectSet.newBuilder()).apply { block() }._build()
public object AlgebraicSubjectSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.Core.AlgebraicSubjectSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.Core.AlgebraicSubjectSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.Core.AlgebraicSubjectSet = _builder.build()

    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet.Operation operation = 1;</code>
     */
    public var operation: com.authzed.api.v1.Core.AlgebraicSubjectSet.Operation
      @JvmName("getOperation")
      get() = _builder.getOperation()
      @JvmName("setOperation")
      set(value) {
        _builder.setOperation(value)
      }
    /**
     * <code>.authzed.api.v1.AlgebraicSubjectSet.Operation operation = 1;</code>
     */
    public fun clearOperation() {
      _builder.clearOperation()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChildrenProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     */
     public val children: com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getChildrenList()
      )
    /**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     * @param value The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addChildren")
    public fun com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>.add(value: com.authzed.api.v1.Core.PermissionRelationshipTree) {
      _builder.addChildren(value)
    }/**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     * @param value The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignChildren")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>.plusAssign(value: com.authzed.api.v1.Core.PermissionRelationshipTree) {
      add(value)
    }/**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     * @param values The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllChildren")
    public fun com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>.addAll(values: kotlin.collections.Iterable<com.authzed.api.v1.Core.PermissionRelationshipTree>) {
      _builder.addAllChildren(values)
    }/**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     * @param values The children to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllChildren")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>.plusAssign(values: kotlin.collections.Iterable<com.authzed.api.v1.Core.PermissionRelationshipTree>) {
      addAll(values)
    }/**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     * @param index The index to set the value at.
     * @param value The children to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setChildren")
    public operator fun com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>.set(index: kotlin.Int, value: com.authzed.api.v1.Core.PermissionRelationshipTree) {
      _builder.setChildren(index, value)
    }/**
     * <code>repeated .authzed.api.v1.PermissionRelationshipTree children = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearChildren")
    public fun com.google.protobuf.kotlin.DslList<com.authzed.api.v1.Core.PermissionRelationshipTree, ChildrenProxy>.clear() {
      _builder.clearChildren()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.Core.AlgebraicSubjectSet.copy(block: com.authzed.api.v1.AlgebraicSubjectSetKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.Core.AlgebraicSubjectSet =
  com.authzed.api.v1.AlgebraicSubjectSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()
