//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/permission_service.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun deleteRelationshipsResponse(block: com.authzed.api.v1.DeleteRelationshipsResponseKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse =
  com.authzed.api.v1.DeleteRelationshipsResponseKt.Dsl._create(com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse.newBuilder()).apply { block() }._build()
public object DeleteRelationshipsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse = _builder.build()

    /**
     * <code>.authzed.api.v1.ZedToken deleted_at = 1;</code>
     */
    public var deletedAt: com.authzed.api.v1.Core.ZedToken
      @JvmName("getDeletedAt")
      get() = _builder.getDeletedAt()
      @JvmName("setDeletedAt")
      set(value) {
        _builder.setDeletedAt(value)
      }
    /**
     * <code>.authzed.api.v1.ZedToken deleted_at = 1;</code>
     */
    public fun clearDeletedAt() {
      _builder.clearDeletedAt()
    }
    /**
     * <code>.authzed.api.v1.ZedToken deleted_at = 1;</code>
     * @return Whether the deletedAt field is set.
     */
    public fun hasDeletedAt(): kotlin.Boolean {
      return _builder.hasDeletedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse.copy(block: com.authzed.api.v1.DeleteRelationshipsResponseKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.PermissionService.DeleteRelationshipsResponse =
  com.authzed.api.v1.DeleteRelationshipsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
