//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/permission_service.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun lookupResourcesResponse(block: com.authzed.api.v1.LookupResourcesResponseKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.PermissionService.LookupResourcesResponse =
  com.authzed.api.v1.LookupResourcesResponseKt.Dsl._create(com.authzed.api.v1.PermissionService.LookupResourcesResponse.newBuilder()).apply { block() }._build()
public object LookupResourcesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.PermissionService.LookupResourcesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.PermissionService.LookupResourcesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.PermissionService.LookupResourcesResponse = _builder.build()

    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    public var lookedUpAt: com.authzed.api.v1.Core.ZedToken
      @JvmName("getLookedUpAt")
      get() = _builder.getLookedUpAt()
      @JvmName("setLookedUpAt")
      set(value) {
        _builder.setLookedUpAt(value)
      }
    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     */
    public fun clearLookedUpAt() {
      _builder.clearLookedUpAt()
    }
    /**
     * <code>.authzed.api.v1.ZedToken looked_up_at = 1;</code>
     * @return Whether the lookedUpAt field is set.
     */
    public fun hasLookedUpAt(): kotlin.Boolean {
      return _builder.hasLookedUpAt()
    }

    /**
     * <code>string resource_object_id = 2;</code>
     */
    public var resourceObjectId: kotlin.String
      @JvmName("getResourceObjectId")
      get() = _builder.getResourceObjectId()
      @JvmName("setResourceObjectId")
      set(value) {
        _builder.setResourceObjectId(value)
      }
    /**
     * <code>string resource_object_id = 2;</code>
     */
    public fun clearResourceObjectId() {
      _builder.clearResourceObjectId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.PermissionService.LookupResourcesResponse.copy(block: com.authzed.api.v1.LookupResourcesResponseKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.PermissionService.LookupResourcesResponse =
  com.authzed.api.v1.LookupResourcesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
