//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/permission_service.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun lookupResourcesRequest(block: com.authzed.api.v1.LookupResourcesRequestKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.PermissionService.LookupResourcesRequest =
  com.authzed.api.v1.LookupResourcesRequestKt.Dsl._create(com.authzed.api.v1.PermissionService.LookupResourcesRequest.newBuilder()).apply { block() }._build()
public object LookupResourcesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.PermissionService.LookupResourcesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.PermissionService.LookupResourcesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.PermissionService.LookupResourcesRequest = _builder.build()

    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    public var consistency: com.authzed.api.v1.PermissionService.Consistency
      @JvmName("getConsistency")
      get() = _builder.getConsistency()
      @JvmName("setConsistency")
      set(value) {
        _builder.setConsistency(value)
      }
    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     */
    public fun clearConsistency() {
      _builder.clearConsistency()
    }
    /**
     * <code>.authzed.api.v1.Consistency consistency = 1;</code>
     * @return Whether the consistency field is set.
     */
    public fun hasConsistency(): kotlin.Boolean {
      return _builder.hasConsistency()
    }

    /**
     * <pre>
     * resource_object_type is the type of resource object for which the IDs will
     * be returned.
     * </pre>
     *
     * <code>string resource_object_type = 2 [(.validate.rules) = { ... }</code>
     */
    public var resourceObjectType: kotlin.String
      @JvmName("getResourceObjectType")
      get() = _builder.getResourceObjectType()
      @JvmName("setResourceObjectType")
      set(value) {
        _builder.setResourceObjectType(value)
      }
    /**
     * <pre>
     * resource_object_type is the type of resource object for which the IDs will
     * be returned.
     * </pre>
     *
     * <code>string resource_object_type = 2 [(.validate.rules) = { ... }</code>
     */
    public fun clearResourceObjectType() {
      _builder.clearResourceObjectType()
    }

    /**
     * <pre>
     * permission is the name of the permission or relation for which the subject
     * must Check.
     * </pre>
     *
     * <code>string permission = 3 [(.validate.rules) = { ... }</code>
     */
    public var permission: kotlin.String
      @JvmName("getPermission")
      get() = _builder.getPermission()
      @JvmName("setPermission")
      set(value) {
        _builder.setPermission(value)
      }
    /**
     * <pre>
     * permission is the name of the permission or relation for which the subject
     * must Check.
     * </pre>
     *
     * <code>string permission = 3 [(.validate.rules) = { ... }</code>
     */
    public fun clearPermission() {
      _builder.clearPermission()
    }

    /**
     * <pre>
     * subject is the subject with access to the resources.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 4 [(.validate.rules) = { ... }</code>
     */
    public var subject: com.authzed.api.v1.Core.SubjectReference
      @JvmName("getSubject")
      get() = _builder.getSubject()
      @JvmName("setSubject")
      set(value) {
        _builder.setSubject(value)
      }
    /**
     * <pre>
     * subject is the subject with access to the resources.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 4 [(.validate.rules) = { ... }</code>
     */
    public fun clearSubject() {
      _builder.clearSubject()
    }
    /**
     * <pre>
     * subject is the subject with access to the resources.
     * </pre>
     *
     * <code>.authzed.api.v1.SubjectReference subject = 4 [(.validate.rules) = { ... }</code>
     * @return Whether the subject field is set.
     */
    public fun hasSubject(): kotlin.Boolean {
      return _builder.hasSubject()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.PermissionService.LookupResourcesRequest.copy(block: com.authzed.api.v1.LookupResourcesRequestKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.PermissionService.LookupResourcesRequest =
  com.authzed.api.v1.LookupResourcesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
