//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/core.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun objectReference(block: com.authzed.api.v1.ObjectReferenceKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.Core.ObjectReference =
  com.authzed.api.v1.ObjectReferenceKt.Dsl._create(com.authzed.api.v1.Core.ObjectReference.newBuilder()).apply { block() }._build()
public object ObjectReferenceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.Core.ObjectReference.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.Core.ObjectReference.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.Core.ObjectReference = _builder.build()

    /**
     * <code>string object_type = 1 [(.validate.rules) = { ... }</code>
     */
    public var objectType: kotlin.String
      @JvmName("getObjectType")
      get() = _builder.getObjectType()
      @JvmName("setObjectType")
      set(value) {
        _builder.setObjectType(value)
      }
    /**
     * <code>string object_type = 1 [(.validate.rules) = { ... }</code>
     */
    public fun clearObjectType() {
      _builder.clearObjectType()
    }

    /**
     * <code>string object_id = 2 [(.validate.rules) = { ... }</code>
     */
    public var objectId: kotlin.String
      @JvmName("getObjectId")
      get() = _builder.getObjectId()
      @JvmName("setObjectId")
      set(value) {
        _builder.setObjectId(value)
      }
    /**
     * <code>string object_id = 2 [(.validate.rules) = { ... }</code>
     */
    public fun clearObjectId() {
      _builder.clearObjectId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.Core.ObjectReference.copy(block: com.authzed.api.v1.ObjectReferenceKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.Core.ObjectReference =
  com.authzed.api.v1.ObjectReferenceKt.Dsl._create(this.toBuilder()).apply { block() }._build()
