//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/watch_service.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun watchRequest(block: com.authzed.api.v1.WatchRequestKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.WatchServiceOuterClass.WatchRequest =
  com.authzed.api.v1.WatchRequestKt.Dsl._create(com.authzed.api.v1.WatchServiceOuterClass.WatchRequest.newBuilder()).apply { block() }._build()
public object WatchRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.WatchServiceOuterClass.WatchRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.WatchServiceOuterClass.WatchRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.WatchServiceOuterClass.WatchRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OptionalObjectTypesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     * @return A list containing the optionalObjectTypes.
     */
    public val optionalObjectTypes: com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOptionalObjectTypesList()
      )
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     * @param value The optionalObjectTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOptionalObjectTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>.add(value: kotlin.String) {
      _builder.addOptionalObjectTypes(value)
    }
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     * @param value The optionalObjectTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOptionalObjectTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     * @param values The optionalObjectTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOptionalObjectTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllOptionalObjectTypes(values)
    }
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     * @param values The optionalObjectTypes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOptionalObjectTypes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     * @param index The index to set the value at.
     * @param value The optionalObjectTypes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOptionalObjectTypes")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setOptionalObjectTypes(index, value)
    }/**
     * <code>repeated string optional_object_types = 1 [(.validate.rules) = { ... }</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOptionalObjectTypes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OptionalObjectTypesProxy>.clear() {
      _builder.clearOptionalObjectTypes()
    }
    /**
     * <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     */
    public var optionalStartCursor: com.authzed.api.v1.Core.ZedToken
      @JvmName("getOptionalStartCursor")
      get() = _builder.getOptionalStartCursor()
      @JvmName("setOptionalStartCursor")
      set(value) {
        _builder.setOptionalStartCursor(value)
      }
    /**
     * <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     */
    public fun clearOptionalStartCursor() {
      _builder.clearOptionalStartCursor()
    }
    /**
     * <code>.authzed.api.v1.ZedToken optional_start_cursor = 2;</code>
     * @return Whether the optionalStartCursor field is set.
     */
    public fun hasOptionalStartCursor(): kotlin.Boolean {
      return _builder.hasOptionalStartCursor()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.WatchServiceOuterClass.WatchRequest.copy(block: com.authzed.api.v1.WatchRequestKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.WatchServiceOuterClass.WatchRequest =
  com.authzed.api.v1.WatchRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
