//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/schema_service.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun writeSchemaResponse(block: com.authzed.api.v1.WriteSchemaResponseKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse =
  com.authzed.api.v1.WriteSchemaResponseKt.Dsl._create(com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse.newBuilder()).apply { block() }._build()
public object WriteSchemaResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse.copy(block: com.authzed.api.v1.WriteSchemaResponseKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.SchemaServiceOuterClass.WriteSchemaResponse =
  com.authzed.api.v1.WriteSchemaResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
