//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: authzed/api/v1/core.proto

package com.authzed.api.v1;

@kotlin.jvm.JvmSynthetic
public inline fun zedToken(block: com.authzed.api.v1.ZedTokenKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.Core.ZedToken =
  com.authzed.api.v1.ZedTokenKt.Dsl._create(com.authzed.api.v1.Core.ZedToken.newBuilder()).apply { block() }._build()
public object ZedTokenKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.authzed.api.v1.Core.ZedToken.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.authzed.api.v1.Core.ZedToken.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.authzed.api.v1.Core.ZedToken = _builder.build()

    /**
     * <code>string token = 1 [(.validate.rules) = { ... }</code>
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <code>string token = 1 [(.validate.rules) = { ... }</code>
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.authzed.api.v1.Core.ZedToken.copy(block: com.authzed.api.v1.ZedTokenKt.Dsl.() -> kotlin.Unit): com.authzed.api.v1.Core.ZedToken =
  com.authzed.api.v1.ZedTokenKt.Dsl._create(this.toBuilder()).apply { block() }._build()
