//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun contact(block: grpc.gateway.protoc_gen_openapiv2.options.ContactKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact =
  grpc.gateway.protoc_gen_openapiv2.options.ContactKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact.newBuilder()).apply { block() }._build()
public object ContactKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact = _builder.build()

    /**
     * <pre>
     * The identifying name of the contact person/organization.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * The identifying name of the contact person/organization.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <pre>
     * The URL pointing to the contact information. MUST be in the format of a
     * URL.
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * <pre>
     * The URL pointing to the contact information. MUST be in the format of a
     * URL.
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * <pre>
     * The email address of the contact person/organization. MUST be in the format
     * of an email address.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <pre>
     * The email address of the contact person/organization. MUST be in the format
     * of an email address.
     * </pre>
     *
     * <code>string email = 3;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact.copy(block: grpc.gateway.protoc_gen_openapiv2.options.ContactKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Contact =
  grpc.gateway.protoc_gen_openapiv2.options.ContactKt.Dsl._create(this.toBuilder()).apply { block() }._build()
