//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun externalDocumentation(block: grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentationKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation =
  grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentationKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation.newBuilder()).apply { block() }._build()
public object ExternalDocumentationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation = _builder.build()

    /**
     * <pre>
     * A short description of the target documentation. GFM syntax can be used for
     * rich text representation.
     * </pre>
     *
     * <code>string description = 1;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * A short description of the target documentation. GFM syntax can be used for
     * rich text representation.
     * </pre>
     *
     * <code>string description = 1;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <pre>
     * The URL for the target documentation. Value MUST be in the format
     * of a URL.
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * <pre>
     * The URL for the target documentation. Value MUST be in the format
     * of a URL.
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation.copy(block: grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentationKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation =
  grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentationKt.Dsl._create(this.toBuilder()).apply { block() }._build()
