//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun header(block: grpc.gateway.protoc_gen_openapiv2.options.HeaderKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header =
  grpc.gateway.protoc_gen_openapiv2.options.HeaderKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header.newBuilder()).apply { block() }._build()
public object HeaderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header = _builder.build()

    /**
     * <pre>
     * `Description` is a short description of the header.
     * </pre>
     *
     * <code>string description = 1;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * `Description` is a short description of the header.
     * </pre>
     *
     * <code>string description = 1;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <pre>
     * The type of the object. The value MUST be one of "string", "number", "integer", or "boolean". The "array" type is not supported.
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public var type: kotlin.String
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <pre>
     * The type of the object. The value MUST be one of "string", "number", "integer", or "boolean". The "array" type is not supported.
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * <pre>
     * `Format` The extending format for the previously mentioned type.
     * </pre>
     *
     * <code>string format = 3;</code>
     */
    public var format: kotlin.String
      @JvmName("getFormat")
      get() = _builder.getFormat()
      @JvmName("setFormat")
      set(value) {
        _builder.setFormat(value)
      }
    /**
     * <pre>
     * `Format` The extending format for the previously mentioned type.
     * </pre>
     *
     * <code>string format = 3;</code>
     */
    public fun clearFormat() {
      _builder.clearFormat()
    }

    /**
     * <pre>
     * `Default` Declares the value of the header that the server will use if none is provided.
     * See: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-6.2.
     * Unlike JSON Schema this value MUST conform to the defined type for the header.
     * </pre>
     *
     * <code>string default = 6;</code>
     */
    public var default: kotlin.String
      @JvmName("getDefault")
      get() = _builder.getDefault()
      @JvmName("setDefault")
      set(value) {
        _builder.setDefault(value)
      }
    /**
     * <pre>
     * `Default` Declares the value of the header that the server will use if none is provided.
     * See: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-6.2.
     * Unlike JSON Schema this value MUST conform to the defined type for the header.
     * </pre>
     *
     * <code>string default = 6;</code>
     */
    public fun clearDefault() {
      _builder.clearDefault()
    }

    /**
     * <pre>
     * 'Pattern' See https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3.
     * </pre>
     *
     * <code>string pattern = 13;</code>
     */
    public var pattern: kotlin.String
      @JvmName("getPattern")
      get() = _builder.getPattern()
      @JvmName("setPattern")
      set(value) {
        _builder.setPattern(value)
      }
    /**
     * <pre>
     * 'Pattern' See https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3.
     * </pre>
     *
     * <code>string pattern = 13;</code>
     */
    public fun clearPattern() {
      _builder.clearPattern()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header.copy(block: grpc.gateway.protoc_gen_openapiv2.options.HeaderKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header =
  grpc.gateway.protoc_gen_openapiv2.options.HeaderKt.Dsl._create(this.toBuilder()).apply { block() }._build()
