//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun jSONSchema(block: grpc.gateway.protoc_gen_openapiv2.options.JSONSchemaKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema =
  grpc.gateway.protoc_gen_openapiv2.options.JSONSchemaKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.newBuilder()).apply { block() }._build()
public object JSONSchemaKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema = _builder.build()

    /**
     * <pre>
     * Ref is used to define an external reference to include in the message.
     * This could be a fully qualified proto message reference, and that type must
     * be imported into the protofile. If no message is identified, the Ref will
     * be used verbatim in the output.
     * For example:
     *  `ref: ".google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>string ref = 3;</code>
     */
    public var ref: kotlin.String
      @JvmName("getRef")
      get() = _builder.getRef()
      @JvmName("setRef")
      set(value) {
        _builder.setRef(value)
      }
    /**
     * <pre>
     * Ref is used to define an external reference to include in the message.
     * This could be a fully qualified proto message reference, and that type must
     * be imported into the protofile. If no message is identified, the Ref will
     * be used verbatim in the output.
     * For example:
     *  `ref: ".google.protobuf.Timestamp"`.
     * </pre>
     *
     * <code>string ref = 3;</code>
     */
    public fun clearRef() {
      _builder.clearRef()
    }

    /**
     * <pre>
     * The title of the schema.
     * </pre>
     *
     * <code>string title = 5;</code>
     */
    public var title: kotlin.String
      @JvmName("getTitle")
      get() = _builder.getTitle()
      @JvmName("setTitle")
      set(value) {
        _builder.setTitle(value)
      }
    /**
     * <pre>
     * The title of the schema.
     * </pre>
     *
     * <code>string title = 5;</code>
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * <pre>
     * A short description of the schema.
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * A short description of the schema.
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <code>string default = 7;</code>
     */
    public var default: kotlin.String
      @JvmName("getDefault")
      get() = _builder.getDefault()
      @JvmName("setDefault")
      set(value) {
        _builder.setDefault(value)
      }
    /**
     * <code>string default = 7;</code>
     */
    public fun clearDefault() {
      _builder.clearDefault()
    }

    /**
     * <code>bool read_only = 8;</code>
     */
    public var readOnly: kotlin.Boolean
      @JvmName("getReadOnly")
      get() = _builder.getReadOnly()
      @JvmName("setReadOnly")
      set(value) {
        _builder.setReadOnly(value)
      }
    /**
     * <code>bool read_only = 8;</code>
     */
    public fun clearReadOnly() {
      _builder.clearReadOnly()
    }

    /**
     * <pre>
     * A free-form property to include a JSON example of this field. This is copied
     * verbatim to the output swagger.json. Quotes must be escaped.
     * This property is the same for 2.0 and 3.0.0 https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/3.0.0.md#schemaObject  https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
     * </pre>
     *
     * <code>string example = 9;</code>
     */
    public var example: kotlin.String
      @JvmName("getExample")
      get() = _builder.getExample()
      @JvmName("setExample")
      set(value) {
        _builder.setExample(value)
      }
    /**
     * <pre>
     * A free-form property to include a JSON example of this field. This is copied
     * verbatim to the output swagger.json. Quotes must be escaped.
     * This property is the same for 2.0 and 3.0.0 https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/3.0.0.md#schemaObject  https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#schemaObject
     * </pre>
     *
     * <code>string example = 9;</code>
     */
    public fun clearExample() {
      _builder.clearExample()
    }

    /**
     * <code>double multiple_of = 10;</code>
     */
    public var multipleOf: kotlin.Double
      @JvmName("getMultipleOf")
      get() = _builder.getMultipleOf()
      @JvmName("setMultipleOf")
      set(value) {
        _builder.setMultipleOf(value)
      }
    /**
     * <code>double multiple_of = 10;</code>
     */
    public fun clearMultipleOf() {
      _builder.clearMultipleOf()
    }

    /**
     * <pre>
     * Maximum represents an inclusive upper limit for a numeric instance. The 
     * value of MUST be a number, 
     * </pre>
     *
     * <code>double maximum = 11;</code>
     */
    public var maximum: kotlin.Double
      @JvmName("getMaximum")
      get() = _builder.getMaximum()
      @JvmName("setMaximum")
      set(value) {
        _builder.setMaximum(value)
      }
    /**
     * <pre>
     * Maximum represents an inclusive upper limit for a numeric instance. The 
     * value of MUST be a number, 
     * </pre>
     *
     * <code>double maximum = 11;</code>
     */
    public fun clearMaximum() {
      _builder.clearMaximum()
    }

    /**
     * <code>bool exclusive_maximum = 12;</code>
     */
    public var exclusiveMaximum: kotlin.Boolean
      @JvmName("getExclusiveMaximum")
      get() = _builder.getExclusiveMaximum()
      @JvmName("setExclusiveMaximum")
      set(value) {
        _builder.setExclusiveMaximum(value)
      }
    /**
     * <code>bool exclusive_maximum = 12;</code>
     */
    public fun clearExclusiveMaximum() {
      _builder.clearExclusiveMaximum()
    }

    /**
     * <pre>
     * minimum represents an inclusive lower limit for a numeric instance. The 
     * value of MUST be a number, 
     * </pre>
     *
     * <code>double minimum = 13;</code>
     */
    public var minimum: kotlin.Double
      @JvmName("getMinimum")
      get() = _builder.getMinimum()
      @JvmName("setMinimum")
      set(value) {
        _builder.setMinimum(value)
      }
    /**
     * <pre>
     * minimum represents an inclusive lower limit for a numeric instance. The 
     * value of MUST be a number, 
     * </pre>
     *
     * <code>double minimum = 13;</code>
     */
    public fun clearMinimum() {
      _builder.clearMinimum()
    }

    /**
     * <code>bool exclusive_minimum = 14;</code>
     */
    public var exclusiveMinimum: kotlin.Boolean
      @JvmName("getExclusiveMinimum")
      get() = _builder.getExclusiveMinimum()
      @JvmName("setExclusiveMinimum")
      set(value) {
        _builder.setExclusiveMinimum(value)
      }
    /**
     * <code>bool exclusive_minimum = 14;</code>
     */
    public fun clearExclusiveMinimum() {
      _builder.clearExclusiveMinimum()
    }

    /**
     * <code>uint64 max_length = 15;</code>
     */
    public var maxLength: kotlin.Long
      @JvmName("getMaxLength")
      get() = _builder.getMaxLength()
      @JvmName("setMaxLength")
      set(value) {
        _builder.setMaxLength(value)
      }
    /**
     * <code>uint64 max_length = 15;</code>
     */
    public fun clearMaxLength() {
      _builder.clearMaxLength()
    }

    /**
     * <code>uint64 min_length = 16;</code>
     */
    public var minLength: kotlin.Long
      @JvmName("getMinLength")
      get() = _builder.getMinLength()
      @JvmName("setMinLength")
      set(value) {
        _builder.setMinLength(value)
      }
    /**
     * <code>uint64 min_length = 16;</code>
     */
    public fun clearMinLength() {
      _builder.clearMinLength()
    }

    /**
     * <code>string pattern = 17;</code>
     */
    public var pattern: kotlin.String
      @JvmName("getPattern")
      get() = _builder.getPattern()
      @JvmName("setPattern")
      set(value) {
        _builder.setPattern(value)
      }
    /**
     * <code>string pattern = 17;</code>
     */
    public fun clearPattern() {
      _builder.clearPattern()
    }

    /**
     * <code>uint64 max_items = 20;</code>
     */
    public var maxItems: kotlin.Long
      @JvmName("getMaxItems")
      get() = _builder.getMaxItems()
      @JvmName("setMaxItems")
      set(value) {
        _builder.setMaxItems(value)
      }
    /**
     * <code>uint64 max_items = 20;</code>
     */
    public fun clearMaxItems() {
      _builder.clearMaxItems()
    }

    /**
     * <code>uint64 min_items = 21;</code>
     */
    public var minItems: kotlin.Long
      @JvmName("getMinItems")
      get() = _builder.getMinItems()
      @JvmName("setMinItems")
      set(value) {
        _builder.setMinItems(value)
      }
    /**
     * <code>uint64 min_items = 21;</code>
     */
    public fun clearMinItems() {
      _builder.clearMinItems()
    }

    /**
     * <code>bool unique_items = 22;</code>
     */
    public var uniqueItems: kotlin.Boolean
      @JvmName("getUniqueItems")
      get() = _builder.getUniqueItems()
      @JvmName("setUniqueItems")
      set(value) {
        _builder.setUniqueItems(value)
      }
    /**
     * <code>bool unique_items = 22;</code>
     */
    public fun clearUniqueItems() {
      _builder.clearUniqueItems()
    }

    /**
     * <code>uint64 max_properties = 24;</code>
     */
    public var maxProperties: kotlin.Long
      @JvmName("getMaxProperties")
      get() = _builder.getMaxProperties()
      @JvmName("setMaxProperties")
      set(value) {
        _builder.setMaxProperties(value)
      }
    /**
     * <code>uint64 max_properties = 24;</code>
     */
    public fun clearMaxProperties() {
      _builder.clearMaxProperties()
    }

    /**
     * <code>uint64 min_properties = 25;</code>
     */
    public var minProperties: kotlin.Long
      @JvmName("getMinProperties")
      get() = _builder.getMinProperties()
      @JvmName("setMinProperties")
      set(value) {
        _builder.setMinProperties(value)
      }
    /**
     * <code>uint64 min_properties = 25;</code>
     */
    public fun clearMinProperties() {
      _builder.clearMinProperties()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RequiredProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string required = 26;</code>
     * @return A list containing the required.
     */
    public val required: com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRequiredList()
      )
    /**
     * <code>repeated string required = 26;</code>
     * @param value The required to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRequired")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>.add(value: kotlin.String) {
      _builder.addRequired(value)
    }
    /**
     * <code>repeated string required = 26;</code>
     * @param value The required to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRequired")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string required = 26;</code>
     * @param values The required to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRequired")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllRequired(values)
    }
    /**
     * <code>repeated string required = 26;</code>
     * @param values The required to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRequired")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string required = 26;</code>
     * @param index The index to set the value at.
     * @param value The required to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRequired")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setRequired(index, value)
    }/**
     * <code>repeated string required = 26;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRequired")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, RequiredProxy>.clear() {
      _builder.clearRequired()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArrayProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     * @return A list containing the array.
     */
    public val array: com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getArrayList()
      )
    /**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     * @param value The array to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArray")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>.add(value: kotlin.String) {
      _builder.addArray(value)
    }
    /**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     * @param value The array to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArray")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     * @param values The array to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArray")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllArray(values)
    }
    /**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     * @param values The array to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArray")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     * @param index The index to set the value at.
     * @param value The array to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArray")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setArray(index, value)
    }/**
     * <pre>
     * Items in 'array' must be unique.
     * </pre>
     *
     * <code>repeated string array = 34;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArray")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ArrayProxy>.clear() {
      _builder.clearArray()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     */
     public val type: com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTypeList()
      )
    /**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     * @param value The type to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addType")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>.add(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes) {
      _builder.addType(value)
    }/**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     * @param value The type to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>.plusAssign(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes) {
      add(value)
    }/**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     * @param values The type to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllType")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>.addAll(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes>) {
      _builder.addAllType(values)
    }/**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     * @param values The type to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>.plusAssign(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes>) {
      addAll(values)
    }/**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     * @param index The index to set the value at.
     * @param value The type to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setType")
    public operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>.set(index: kotlin.Int, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes) {
      _builder.setType(index, value)
    }/**
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.JSONSchema.JSONSchemaSimpleTypes type = 35;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearType")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.JSONSchemaSimpleTypes, TypeProxy>.clear() {
      _builder.clearType()
    }
    /**
     * <pre>
     * `Format`
     * </pre>
     *
     * <code>string format = 36;</code>
     */
    public var format: kotlin.String
      @JvmName("getFormat")
      get() = _builder.getFormat()
      @JvmName("setFormat")
      set(value) {
        _builder.setFormat(value)
      }
    /**
     * <pre>
     * `Format`
     * </pre>
     *
     * <code>string format = 36;</code>
     */
    public fun clearFormat() {
      _builder.clearFormat()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnumProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     * @return A list containing the enum.
     */
    public val enum: com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEnumList()
      )
    /**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     * @param value The enum to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEnum")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>.add(value: kotlin.String) {
      _builder.addEnum(value)
    }
    /**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     * @param value The enum to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEnum")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     * @param values The enum to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEnum")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllEnum(values)
    }
    /**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     * @param values The enum to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEnum")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     * @param index The index to set the value at.
     * @param value The enum to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEnum")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setEnum(index, value)
    }/**
     * <pre>
     * Items in `enum` must be unique https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1
     * </pre>
     *
     * <code>repeated string enum = 46;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEnum")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EnumProxy>.clear() {
      _builder.clearEnum()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema.copy(block: grpc.gateway.protoc_gen_openapiv2.options.JSONSchemaKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.JSONSchema =
  grpc.gateway.protoc_gen_openapiv2.options.JSONSchemaKt.Dsl._create(this.toBuilder()).apply { block() }._build()
