//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun license(block: grpc.gateway.protoc_gen_openapiv2.options.LicenseKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License =
  grpc.gateway.protoc_gen_openapiv2.options.LicenseKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License.newBuilder()).apply { block() }._build()
public object LicenseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License = _builder.build()

    /**
     * <pre>
     * The license name used for the API.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * The license name used for the API.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <pre>
     * A URL to the license used for the API. MUST be in the format of a URL.
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * <pre>
     * A URL to the license used for the API. MUST be in the format of a URL.
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License.copy(block: grpc.gateway.protoc_gen_openapiv2.options.LicenseKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.License =
  grpc.gateway.protoc_gen_openapiv2.options.LicenseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
