//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun operation(block: grpc.gateway.protoc_gen_openapiv2.options.OperationKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation =
  grpc.gateway.protoc_gen_openapiv2.options.OperationKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation.newBuilder()).apply { block() }._build()
public object OperationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTagsList()
      )
    /**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * <pre>
     * A list of tags for API documentation control. Tags can be used for logical
     * grouping of operations by resources or any other qualifier.
     * </pre>
     *
     * <code>repeated string tags = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }
    /**
     * <pre>
     * A short summary of what the operation does. For maximum readability in the
     * swagger-ui, this field SHOULD be less than 120 characters.
     * </pre>
     *
     * <code>string summary = 2;</code>
     */
    public var summary: kotlin.String
      @JvmName("getSummary")
      get() = _builder.getSummary()
      @JvmName("setSummary")
      set(value) {
        _builder.setSummary(value)
      }
    /**
     * <pre>
     * A short summary of what the operation does. For maximum readability in the
     * swagger-ui, this field SHOULD be less than 120 characters.
     * </pre>
     *
     * <code>string summary = 2;</code>
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }

    /**
     * <pre>
     * A verbose explanation of the operation behavior. GFM syntax can be used for
     * rich text representation.
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * A verbose explanation of the operation behavior. GFM syntax can be used for
     * rich text representation.
     * </pre>
     *
     * <code>string description = 3;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <pre>
     * Additional external documentation for this operation.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 4;</code>
     */
    public var externalDocs: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation
      @JvmName("getExternalDocs")
      get() = _builder.getExternalDocs()
      @JvmName("setExternalDocs")
      set(value) {
        _builder.setExternalDocs(value)
      }
    /**
     * <pre>
     * Additional external documentation for this operation.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 4;</code>
     */
    public fun clearExternalDocs() {
      _builder.clearExternalDocs()
    }
    /**
     * <pre>
     * Additional external documentation for this operation.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 4;</code>
     * @return Whether the externalDocs field is set.
     */
    public fun hasExternalDocs(): kotlin.Boolean {
      return _builder.hasExternalDocs()
    }

    /**
     * <pre>
     * Unique string used to identify the operation. The id MUST be unique among
     * all operations described in the API. Tools and libraries MAY use the
     * operationId to uniquely identify an operation, therefore, it is recommended
     * to follow common programming naming conventions.
     * </pre>
     *
     * <code>string operation_id = 5;</code>
     */
    public var operationId: kotlin.String
      @JvmName("getOperationId")
      get() = _builder.getOperationId()
      @JvmName("setOperationId")
      set(value) {
        _builder.setOperationId(value)
      }
    /**
     * <pre>
     * Unique string used to identify the operation. The id MUST be unique among
     * all operations described in the API. Tools and libraries MAY use the
     * operationId to uniquely identify an operation, therefore, it is recommended
     * to follow common programming naming conventions.
     * </pre>
     *
     * <code>string operation_id = 5;</code>
     */
    public fun clearOperationId() {
      _builder.clearOperationId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ConsumesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @return A list containing the consumes.
     */
    public val consumes: com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getConsumesList()
      )
    /**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param value The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addConsumes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.add(value: kotlin.String) {
      _builder.addConsumes(value)
    }
    /**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param value The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignConsumes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param values The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllConsumes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllConsumes(values)
    }
    /**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param values The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllConsumes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param index The index to set the value at.
     * @param value The consumes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setConsumes")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setConsumes(index, value)
    }/**
     * <pre>
     * A list of MIME types the operation can consume. This overrides the consumes
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearConsumes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.clear() {
      _builder.clearConsumes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ProducesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @return A list containing the produces.
     */
    public val produces: com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getProducesList()
      )
    /**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param value The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addProduces")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.add(value: kotlin.String) {
      _builder.addProduces(value)
    }
    /**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param value The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignProduces")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param values The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllProduces")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllProduces(values)
    }
    /**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param values The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllProduces")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param index The index to set the value at.
     * @param value The produces to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setProduces")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setProduces(index, value)
    }/**
     * <pre>
     * A list of MIME types the operation can produce. This overrides the produces
     * definition at the OpenAPI Object. An empty value MAY be used to clear the
     * global definition. Value MUST be as described under Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearProduces")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.clear() {
      _builder.clearProduces()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResponsesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The list of possible responses as they are returned from executing this
     * operation.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 9;</code>
     */
     public val responses: com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getResponsesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getResponsesMap()
      )
    /**
     * <pre>
     * The list of possible responses as they are returned from executing this
     * operation.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 9;</code>
     */
    @JvmName("putResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .put(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response) {
         _builder.putResponses(key, value)
       }
    /**
     * <pre>
     * The list of possible responses as they are returned from executing this
     * operation.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setResponses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .set(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response) {
         put(key, value)
       }
    /**
     * <pre>
     * The list of possible responses as they are returned from executing this
     * operation.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .remove(key: kotlin.String) {
         _builder.removeResponses(key)
       }
    /**
     * <pre>
     * The list of possible responses as they are returned from executing this
     * operation.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response>) {
         _builder.putAllResponses(map)
       }
    /**
     * <pre>
     * The list of possible responses as they are returned from executing this
     * operation.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .clear() {
         _builder.clearResponses()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SchemesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     */
     public val schemes: com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSchemesList()
      )
    /**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @param value The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSchemes")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.add(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme) {
      _builder.addSchemes(value)
    }/**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @param value The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSchemes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.plusAssign(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme) {
      add(value)
    }/**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @param values The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSchemes")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.addAll(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme>) {
      _builder.addAllSchemes(values)
    }/**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @param values The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSchemes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.plusAssign(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme>) {
      addAll(values)
    }/**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     * @param index The index to set the value at.
     * @param value The schemes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSchemes")
    public operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.set(index: kotlin.Int, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme) {
      _builder.setSchemes(index, value)
    }/**
     * <pre>
     * The transfer protocol for the operation. Values MUST be from the list:
     * "http", "https", "ws", "wss". The value overrides the OpenAPI Object
     * schemes definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSchemes")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.clear() {
      _builder.clearSchemes()
    }
    /**
     * <pre>
     * Declares this operation to be deprecated. Usage of the declared operation
     * should be refrained. Default value is false.
     * </pre>
     *
     * <code>bool deprecated = 11;</code>
     */
    public var deprecated: kotlin.Boolean
      @JvmName("getDeprecated")
      get() = _builder.getDeprecated()
      @JvmName("setDeprecated")
      set(value) {
        _builder.setDeprecated(value)
      }
    /**
     * <pre>
     * Declares this operation to be deprecated. Usage of the declared operation
     * should be refrained. Default value is false.
     * </pre>
     *
     * <code>bool deprecated = 11;</code>
     */
    public fun clearDeprecated() {
      _builder.clearDeprecated()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SecurityProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     */
     public val security: com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSecurityList()
      )
    /**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param value The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSecurity")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.add(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement) {
      _builder.addSecurity(value)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param value The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSecurity")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.plusAssign(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement) {
      add(value)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param values The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSecurity")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.addAll(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement>) {
      _builder.addAllSecurity(values)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param values The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSecurity")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.plusAssign(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement>) {
      addAll(values)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param index The index to set the value at.
     * @param value The security to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSecurity")
    public operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.set(index: kotlin.Int, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement) {
      _builder.setSecurity(index, value)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for this operation. The
     * list of values describes alternative security schemes that can be used
     * (that is, there is a logical OR between the security requirements). This
     * definition overrides any declared top-level security. To remove a top-level
     * security declaration, an empty array can be used.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSecurity")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.clear() {
      _builder.clearSecurity()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 13;</code>
     */
     public val extensions: com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getExtensionsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getExtensionsMap()
      )
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 13;</code>
     */
    @JvmName("putExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .put(key: kotlin.String, value: com.google.protobuf.Value) {
         _builder.putExtensions(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setExtensions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .set(key: kotlin.String, value: com.google.protobuf.Value) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .remove(key: kotlin.String) {
         _builder.removeExtensions(key)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, com.google.protobuf.Value>) {
         _builder.putAllExtensions(map)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .clear() {
         _builder.clearExtensions()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation.copy(block: grpc.gateway.protoc_gen_openapiv2.options.OperationKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Operation =
  grpc.gateway.protoc_gen_openapiv2.options.OperationKt.Dsl._create(this.toBuilder()).apply { block() }._build()
