//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun response(block: grpc.gateway.protoc_gen_openapiv2.options.ResponseKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response =
  grpc.gateway.protoc_gen_openapiv2.options.ResponseKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response.newBuilder()).apply { block() }._build()
public object ResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response = _builder.build()

    /**
     * <pre>
     * `Description` is a short description of the response.
     * GFM syntax can be used for rich text representation.
     * </pre>
     *
     * <code>string description = 1;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * `Description` is a short description of the response.
     * GFM syntax can be used for rich text representation.
     * </pre>
     *
     * <code>string description = 1;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <pre>
     * `Schema` optionally defines the structure of the response.
     * If `Schema` is not provided, it means there is no content to the response.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Schema schema = 2;</code>
     */
    public var schema: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Schema
      @JvmName("getSchema")
      get() = _builder.getSchema()
      @JvmName("setSchema")
      set(value) {
        _builder.setSchema(value)
      }
    /**
     * <pre>
     * `Schema` optionally defines the structure of the response.
     * If `Schema` is not provided, it means there is no content to the response.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Schema schema = 2;</code>
     */
    public fun clearSchema() {
      _builder.clearSchema()
    }
    /**
     * <pre>
     * `Schema` optionally defines the structure of the response.
     * If `Schema` is not provided, it means there is no content to the response.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Schema schema = 2;</code>
     * @return Whether the schema field is set.
     */
    public fun hasSchema(): kotlin.Boolean {
      return _builder.hasSchema()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HeadersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * `Headers` A list of headers that are sent with the response.
     * `Header` name is expected to be a string in the canonical format of the MIME header key
     * See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Header&gt; headers = 3;</code>
     */
     public val headers: com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header, HeadersProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getHeadersMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getHeadersMap()
      )
    /**
     * <pre>
     * `Headers` A list of headers that are sent with the response.
     * `Header` name is expected to be a string in the canonical format of the MIME header key
     * See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Header&gt; headers = 3;</code>
     */
    @JvmName("putHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header, HeadersProxy>
      .put(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header) {
         _builder.putHeaders(key, value)
       }
    /**
     * <pre>
     * `Headers` A list of headers that are sent with the response.
     * `Header` name is expected to be a string in the canonical format of the MIME header key
     * See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Header&gt; headers = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header, HeadersProxy>
      .set(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header) {
         put(key, value)
       }
    /**
     * <pre>
     * `Headers` A list of headers that are sent with the response.
     * `Header` name is expected to be a string in the canonical format of the MIME header key
     * See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Header&gt; headers = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header, HeadersProxy>
      .remove(key: kotlin.String) {
         _builder.removeHeaders(key)
       }
    /**
     * <pre>
     * `Headers` A list of headers that are sent with the response.
     * `Header` name is expected to be a string in the canonical format of the MIME header key
     * See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Header&gt; headers = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header, HeadersProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header>) {
         _builder.putAllHeaders(map)
       }
    /**
     * <pre>
     * `Headers` A list of headers that are sent with the response.
     * `Header` name is expected to be a string in the canonical format of the MIME header key
     * See: https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Header&gt; headers = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearHeaders")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Header, HeadersProxy>
      .clear() {
         _builder.clearHeaders()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExamplesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * `Examples` gives per-mimetype response examples.
     * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
     * </pre>
     *
     * <code>map&lt;string, string&gt; examples = 4;</code>
     */
     public val examples: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExamplesProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getExamplesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getExamplesMap()
      )
    /**
     * <pre>
     * `Examples` gives per-mimetype response examples.
     * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
     * </pre>
     *
     * <code>map&lt;string, string&gt; examples = 4;</code>
     */
    @JvmName("putExamples")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExamplesProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putExamples(key, value)
       }
    /**
     * <pre>
     * `Examples` gives per-mimetype response examples.
     * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
     * </pre>
     *
     * <code>map&lt;string, string&gt; examples = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setExamples")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExamplesProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * <pre>
     * `Examples` gives per-mimetype response examples.
     * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
     * </pre>
     *
     * <code>map&lt;string, string&gt; examples = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeExamples")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExamplesProxy>
      .remove(key: kotlin.String) {
         _builder.removeExamples(key)
       }
    /**
     * <pre>
     * `Examples` gives per-mimetype response examples.
     * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
     * </pre>
     *
     * <code>map&lt;string, string&gt; examples = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllExamples")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExamplesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllExamples(map)
       }
    /**
     * <pre>
     * `Examples` gives per-mimetype response examples.
     * See: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0/versions/2.0.md#example-object
     * </pre>
     *
     * <code>map&lt;string, string&gt; examples = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearExamples")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, ExamplesProxy>
      .clear() {
         _builder.clearExamples()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 5;</code>
     */
     public val extensions: com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getExtensionsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getExtensionsMap()
      )
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 5;</code>
     */
    @JvmName("putExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .put(key: kotlin.String, value: com.google.protobuf.Value) {
         _builder.putExtensions(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setExtensions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .set(key: kotlin.String, value: com.google.protobuf.Value) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .remove(key: kotlin.String) {
         _builder.removeExtensions(key)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, com.google.protobuf.Value>) {
         _builder.putAllExtensions(map)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .clear() {
         _builder.clearExtensions()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response.copy(block: grpc.gateway.protoc_gen_openapiv2.options.ResponseKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response =
  grpc.gateway.protoc_gen_openapiv2.options.ResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
