//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun securityScheme(block: grpc.gateway.protoc_gen_openapiv2.options.SecuritySchemeKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme =
  grpc.gateway.protoc_gen_openapiv2.options.SecuritySchemeKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.newBuilder()).apply { block() }._build()
public object SecuritySchemeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme = _builder.build()

    /**
     * <pre>
     * The type of the security scheme. Valid values are "basic",
     * "apiKey" or "oauth2".
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type type = 1;</code>
     */
    public var type: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.Type
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <pre>
     * The type of the security scheme. Valid values are "basic",
     * "apiKey" or "oauth2".
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Type type = 1;</code>
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * <pre>
     * A short description for security scheme.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * A short description for security scheme.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <pre>
     * The name of the header or query parameter to be used.
     * Valid for apiKey.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * The name of the header or query parameter to be used.
     * Valid for apiKey.
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <pre>
     * The location of the API key. Valid values are "query" or
     * "header".
     * Valid for apiKey.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In in = 4;</code>
     */
    public var in_: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.In
      @JvmName("getIn_")
      get() = _builder.getIn()
      @JvmName("setIn_")
      set(value) {
        _builder.setIn(value)
      }
    /**
     * <pre>
     * The location of the API key. Valid values are "query" or
     * "header".
     * Valid for apiKey.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.In in = 4;</code>
     */
    public fun clearIn_() {
      _builder.clearIn()
    }

    /**
     * <pre>
     * The flow used by the OAuth2 security scheme. Valid values are
     * "implicit", "password", "application" or "accessCode".
     * Valid for oauth2.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow flow = 5;</code>
     */
    public var flow: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.Flow
      @JvmName("getFlow")
      get() = _builder.getFlow()
      @JvmName("setFlow")
      set(value) {
        _builder.setFlow(value)
      }
    /**
     * <pre>
     * The flow used by the OAuth2 security scheme. Valid values are
     * "implicit", "password", "application" or "accessCode".
     * Valid for oauth2.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme.Flow flow = 5;</code>
     */
    public fun clearFlow() {
      _builder.clearFlow()
    }

    /**
     * <pre>
     * The authorization URL to be used for this flow. This SHOULD be in
     * the form of a URL.
     * Valid for oauth2/implicit and oauth2/accessCode.
     * </pre>
     *
     * <code>string authorization_url = 6;</code>
     */
    public var authorizationUrl: kotlin.String
      @JvmName("getAuthorizationUrl")
      get() = _builder.getAuthorizationUrl()
      @JvmName("setAuthorizationUrl")
      set(value) {
        _builder.setAuthorizationUrl(value)
      }
    /**
     * <pre>
     * The authorization URL to be used for this flow. This SHOULD be in
     * the form of a URL.
     * Valid for oauth2/implicit and oauth2/accessCode.
     * </pre>
     *
     * <code>string authorization_url = 6;</code>
     */
    public fun clearAuthorizationUrl() {
      _builder.clearAuthorizationUrl()
    }

    /**
     * <pre>
     * The token URL to be used for this flow. This SHOULD be in the
     * form of a URL.
     * Valid for oauth2/password, oauth2/application and oauth2/accessCode.
     * </pre>
     *
     * <code>string token_url = 7;</code>
     */
    public var tokenUrl: kotlin.String
      @JvmName("getTokenUrl")
      get() = _builder.getTokenUrl()
      @JvmName("setTokenUrl")
      set(value) {
        _builder.setTokenUrl(value)
      }
    /**
     * <pre>
     * The token URL to be used for this flow. This SHOULD be in the
     * form of a URL.
     * Valid for oauth2/password, oauth2/application and oauth2/accessCode.
     * </pre>
     *
     * <code>string token_url = 7;</code>
     */
    public fun clearTokenUrl() {
      _builder.clearTokenUrl()
    }

    /**
     * <pre>
     * The available scopes for the OAuth2 security scheme.
     * Valid for oauth2.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Scopes scopes = 8;</code>
     */
    public var scopes: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scopes
      @JvmName("getScopes")
      get() = _builder.getScopes()
      @JvmName("setScopes")
      set(value) {
        _builder.setScopes(value)
      }
    /**
     * <pre>
     * The available scopes for the OAuth2 security scheme.
     * Valid for oauth2.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Scopes scopes = 8;</code>
     */
    public fun clearScopes() {
      _builder.clearScopes()
    }
    /**
     * <pre>
     * The available scopes for the OAuth2 security scheme.
     * Valid for oauth2.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Scopes scopes = 8;</code>
     * @return Whether the scopes field is set.
     */
    public fun hasScopes(): kotlin.Boolean {
      return _builder.hasScopes()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 9;</code>
     */
     public val extensions: com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getExtensionsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getExtensionsMap()
      )
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 9;</code>
     */
    @JvmName("putExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .put(key: kotlin.String, value: com.google.protobuf.Value) {
         _builder.putExtensions(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setExtensions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .set(key: kotlin.String, value: com.google.protobuf.Value) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .remove(key: kotlin.String) {
         _builder.removeExtensions(key)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, com.google.protobuf.Value>) {
         _builder.putAllExtensions(map)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .clear() {
         _builder.clearExtensions()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme.copy(block: grpc.gateway.protoc_gen_openapiv2.options.SecuritySchemeKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme =
  grpc.gateway.protoc_gen_openapiv2.options.SecuritySchemeKt.Dsl._create(this.toBuilder()).apply { block() }._build()
