//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun securityDefinitions(block: grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitionsKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions =
  grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitionsKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions.newBuilder()).apply { block() }._build()
public object SecurityDefinitionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SecurityProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A single security scheme definition, mapping a "name" to the scheme it
     * defines.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme&gt; security = 1;</code>
     */
     public val security: com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme, SecurityProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getSecurityMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getSecurityMap()
      )
    /**
     * <pre>
     * A single security scheme definition, mapping a "name" to the scheme it
     * defines.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme&gt; security = 1;</code>
     */
    @JvmName("putSecurity")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme, SecurityProxy>
      .put(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme) {
         _builder.putSecurity(key, value)
       }
    /**
     * <pre>
     * A single security scheme definition, mapping a "name" to the scheme it
     * defines.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme&gt; security = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setSecurity")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme, SecurityProxy>
      .set(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme) {
         put(key, value)
       }
    /**
     * <pre>
     * A single security scheme definition, mapping a "name" to the scheme it
     * defines.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme&gt; security = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeSecurity")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme, SecurityProxy>
      .remove(key: kotlin.String) {
         _builder.removeSecurity(key)
       }
    /**
     * <pre>
     * A single security scheme definition, mapping a "name" to the scheme it
     * defines.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme&gt; security = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllSecurity")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme, SecurityProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme>) {
         _builder.putAllSecurity(map)
       }
    /**
     * <pre>
     * A single security scheme definition, mapping a "name" to the scheme it
     * defines.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.SecurityScheme&gt; security = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearSecurity")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityScheme, SecurityProxy>
      .clear() {
         _builder.clearSecurity()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions.copy(block: grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitionsKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions =
  grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
