//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun swagger(block: grpc.gateway.protoc_gen_openapiv2.options.SwaggerKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger =
  grpc.gateway.protoc_gen_openapiv2.options.SwaggerKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger.newBuilder()).apply { block() }._build()
public object SwaggerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger = _builder.build()

    /**
     * <pre>
     * Specifies the OpenAPI Specification version being used. It can be
     * used by the OpenAPI UI and other clients to interpret the API listing. The 
     * value MUST be "2.0".
     * </pre>
     *
     * <code>string swagger = 1;</code>
     */
    public var swagger: kotlin.String
      @JvmName("getSwagger")
      get() = _builder.getSwagger()
      @JvmName("setSwagger")
      set(value) {
        _builder.setSwagger(value)
      }
    /**
     * <pre>
     * Specifies the OpenAPI Specification version being used. It can be
     * used by the OpenAPI UI and other clients to interpret the API listing. The 
     * value MUST be "2.0".
     * </pre>
     *
     * <code>string swagger = 1;</code>
     */
    public fun clearSwagger() {
      _builder.clearSwagger()
    }

    /**
     * <pre>
     * Provides metadata about the API. The metadata can be used by the 
     * clients if needed.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Info info = 2;</code>
     */
    public var info: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Info
      @JvmName("getInfo")
      get() = _builder.getInfo()
      @JvmName("setInfo")
      set(value) {
        _builder.setInfo(value)
      }
    /**
     * <pre>
     * Provides metadata about the API. The metadata can be used by the 
     * clients if needed.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Info info = 2;</code>
     */
    public fun clearInfo() {
      _builder.clearInfo()
    }
    /**
     * <pre>
     * Provides metadata about the API. The metadata can be used by the 
     * clients if needed.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.Info info = 2;</code>
     * @return Whether the info field is set.
     */
    public fun hasInfo(): kotlin.Boolean {
      return _builder.hasInfo()
    }

    /**
     * <pre>
     * The host (name or ip) serving the API. This MUST be the host only and does 
     * not include the scheme nor sub-paths. It MAY include a port. If the host is
     * not included, the host serving the documentation is to be used (including
     * the port). The host does not support path templating.
     * </pre>
     *
     * <code>string host = 3;</code>
     */
    public var host: kotlin.String
      @JvmName("getHost")
      get() = _builder.getHost()
      @JvmName("setHost")
      set(value) {
        _builder.setHost(value)
      }
    /**
     * <pre>
     * The host (name or ip) serving the API. This MUST be the host only and does 
     * not include the scheme nor sub-paths. It MAY include a port. If the host is
     * not included, the host serving the documentation is to be used (including
     * the port). The host does not support path templating.
     * </pre>
     *
     * <code>string host = 3;</code>
     */
    public fun clearHost() {
      _builder.clearHost()
    }

    /**
     * <pre>
     * The base path on which the API is served, which is relative to the host. If
     * it is not included, the API is served directly under the host. The value 
     * MUST start with a leading slash (/). The basePath does not support path
     * templating.
     * Note that using `base_path` does not change the endpoint paths that are 
     * generated in the resulting OpenAPI file. If you wish to use `base_path`
     * with relatively generated OpenAPI paths, the `base_path` prefix must be 
     * manually removed from your `google.api.http` paths and your code changed to 
     * serve the API from the `base_path`.
     * </pre>
     *
     * <code>string base_path = 4;</code>
     */
    public var basePath: kotlin.String
      @JvmName("getBasePath")
      get() = _builder.getBasePath()
      @JvmName("setBasePath")
      set(value) {
        _builder.setBasePath(value)
      }
    /**
     * <pre>
     * The base path on which the API is served, which is relative to the host. If
     * it is not included, the API is served directly under the host. The value 
     * MUST start with a leading slash (/). The basePath does not support path
     * templating.
     * Note that using `base_path` does not change the endpoint paths that are 
     * generated in the resulting OpenAPI file. If you wish to use `base_path`
     * with relatively generated OpenAPI paths, the `base_path` prefix must be 
     * manually removed from your `google.api.http` paths and your code changed to 
     * serve the API from the `base_path`.
     * </pre>
     *
     * <code>string base_path = 4;</code>
     */
    public fun clearBasePath() {
      _builder.clearBasePath()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SchemesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     */
     public val schemes: com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSchemesList()
      )
    /**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     * @param value The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSchemes")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.add(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme) {
      _builder.addSchemes(value)
    }/**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     * @param value The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSchemes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.plusAssign(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme) {
      add(value)
    }/**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     * @param values The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSchemes")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.addAll(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme>) {
      _builder.addAllSchemes(values)
    }/**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     * @param values The schemes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSchemes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.plusAssign(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme>) {
      addAll(values)
    }/**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     * @param index The index to set the value at.
     * @param value The schemes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSchemes")
    public operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.set(index: kotlin.Int, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme) {
      _builder.setSchemes(index, value)
    }/**
     * <pre>
     * The transfer protocol of the API. Values MUST be from the list: "http",
     * "https", "ws", "wss". If the schemes is not included, the default scheme to
     * be used is the one used to access the OpenAPI definition itself.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.Scheme schemes = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSchemes")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Scheme, SchemesProxy>.clear() {
      _builder.clearSchemes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ConsumesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @return A list containing the consumes.
     */
    public val consumes: com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getConsumesList()
      )
    /**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param value The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addConsumes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.add(value: kotlin.String) {
      _builder.addConsumes(value)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param value The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignConsumes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param values The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllConsumes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllConsumes(values)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param values The consumes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllConsumes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     * @param index The index to set the value at.
     * @param value The consumes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setConsumes")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setConsumes(index, value)
    }/**
     * <pre>
     * A list of MIME types the APIs can consume. This is global to all APIs but 
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string consumes = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearConsumes")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ConsumesProxy>.clear() {
      _builder.clearConsumes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ProducesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @return A list containing the produces.
     */
    public val produces: com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getProducesList()
      )
    /**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param value The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addProduces")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.add(value: kotlin.String) {
      _builder.addProduces(value)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param value The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignProduces")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param values The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllProduces")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllProduces(values)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param values The produces to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllProduces")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     * @param index The index to set the value at.
     * @param value The produces to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setProduces")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setProduces(index, value)
    }/**
     * <pre>
     * A list of MIME types the APIs can produce. This is global to all APIs but
     * can be overridden on specific API calls. Value MUST be as described under
     * Mime Types.
     * </pre>
     *
     * <code>repeated string produces = 7;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearProduces")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ProducesProxy>.clear() {
      _builder.clearProduces()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResponsesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * An object to hold responses that can be used across operations. This
     * property does not define global responses for all operations.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 10;</code>
     */
     public val responses: com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getResponsesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getResponsesMap()
      )
    /**
     * <pre>
     * An object to hold responses that can be used across operations. This
     * property does not define global responses for all operations.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 10;</code>
     */
    @JvmName("putResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .put(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response) {
         _builder.putResponses(key, value)
       }
    /**
     * <pre>
     * An object to hold responses that can be used across operations. This
     * property does not define global responses for all operations.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setResponses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .set(key: kotlin.String, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response) {
         put(key, value)
       }
    /**
     * <pre>
     * An object to hold responses that can be used across operations. This
     * property does not define global responses for all operations.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .remove(key: kotlin.String) {
         _builder.removeResponses(key)
       }
    /**
     * <pre>
     * An object to hold responses that can be used across operations. This
     * property does not define global responses for all operations.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response>) {
         _builder.putAllResponses(map)
       }
    /**
     * <pre>
     * An object to hold responses that can be used across operations. This
     * property does not define global responses for all operations.
     * </pre>
     *
     * <code>map&lt;string, .grpc.gateway.protoc_gen_openapiv2.options.Response&gt; responses = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearResponses")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Response, ResponsesProxy>
      .clear() {
         _builder.clearResponses()
       }

    /**
     * <pre>
     * Security scheme definitions that can be used across the specification.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitions security_definitions = 11;</code>
     */
    public var securityDefinitions: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityDefinitions
      @JvmName("getSecurityDefinitions")
      get() = _builder.getSecurityDefinitions()
      @JvmName("setSecurityDefinitions")
      set(value) {
        _builder.setSecurityDefinitions(value)
      }
    /**
     * <pre>
     * Security scheme definitions that can be used across the specification.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitions security_definitions = 11;</code>
     */
    public fun clearSecurityDefinitions() {
      _builder.clearSecurityDefinitions()
    }
    /**
     * <pre>
     * Security scheme definitions that can be used across the specification.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.SecurityDefinitions security_definitions = 11;</code>
     * @return Whether the securityDefinitions field is set.
     */
    public fun hasSecurityDefinitions(): kotlin.Boolean {
      return _builder.hasSecurityDefinitions()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SecurityProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     */
     public val security: com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getSecurityList()
      )
    /**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param value The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSecurity")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.add(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement) {
      _builder.addSecurity(value)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param value The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSecurity")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.plusAssign(value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement) {
      add(value)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param values The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSecurity")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.addAll(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement>) {
      _builder.addAllSecurity(values)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param values The security to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSecurity")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.plusAssign(values: kotlin.collections.Iterable<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement>) {
      addAll(values)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     * @param index The index to set the value at.
     * @param value The security to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSecurity")
    public operator fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.set(index: kotlin.Int, value: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement) {
      _builder.setSecurity(index, value)
    }/**
     * <pre>
     * A declaration of which security schemes are applied for the API as a whole.
     * The list of values describes alternative security schemes that can be used 
     * (that is, there is a logical OR between the security requirements). 
     * Individual operations can override this definition.
     * </pre>
     *
     * <code>repeated .grpc.gateway.protoc_gen_openapiv2.options.SecurityRequirement security = 12;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSecurity")
    public fun com.google.protobuf.kotlin.DslList<grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.SecurityRequirement, SecurityProxy>.clear() {
      _builder.clearSecurity()
    }
    /**
     * <pre>
     * Additional external documentation.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 14;</code>
     */
    public var externalDocs: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation
      @JvmName("getExternalDocs")
      get() = _builder.getExternalDocs()
      @JvmName("setExternalDocs")
      set(value) {
        _builder.setExternalDocs(value)
      }
    /**
     * <pre>
     * Additional external documentation.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 14;</code>
     */
    public fun clearExternalDocs() {
      _builder.clearExternalDocs()
    }
    /**
     * <pre>
     * Additional external documentation.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 14;</code>
     * @return Whether the externalDocs field is set.
     */
    public fun hasExternalDocs(): kotlin.Boolean {
      return _builder.hasExternalDocs()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 15;</code>
     */
     public val extensions: com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getExtensionsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getExtensionsMap()
      )
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 15;</code>
     */
    @JvmName("putExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .put(key: kotlin.String, value: com.google.protobuf.Value) {
         _builder.putExtensions(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 15;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setExtensions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .set(key: kotlin.String, value: com.google.protobuf.Value) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 15;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .remove(key: kotlin.String) {
         _builder.removeExtensions(key)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 15;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, com.google.protobuf.Value>) {
         _builder.putAllExtensions(map)
       }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; extensions = 15;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearExtensions")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, com.google.protobuf.Value, ExtensionsProxy>
      .clear() {
         _builder.clearExtensions()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger.copy(block: grpc.gateway.protoc_gen_openapiv2.options.SwaggerKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Swagger =
  grpc.gateway.protoc_gen_openapiv2.options.SwaggerKt.Dsl._create(this.toBuilder()).apply { block() }._build()
