//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: protoc-gen-openapiv2/options/openapiv2.proto

package grpc.gateway.protoc_gen_openapiv2.options;

@kotlin.jvm.JvmSynthetic
public inline fun tag(block: grpc.gateway.protoc_gen_openapiv2.options.TagKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag =
  grpc.gateway.protoc_gen_openapiv2.options.TagKt.Dsl._create(grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag.newBuilder()).apply { block() }._build()
public object TagKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag = _builder.build()

    /**
     * <pre>
     * A short description for the tag. GFM syntax can be used for rich text 
     * representation.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public var description: kotlin.String
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <pre>
     * A short description for the tag. GFM syntax can be used for rich text 
     * representation.
     * </pre>
     *
     * <code>string description = 2;</code>
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * <pre>
     * Additional external documentation for this tag.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 3;</code>
     */
    public var externalDocs: grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.ExternalDocumentation
      @JvmName("getExternalDocs")
      get() = _builder.getExternalDocs()
      @JvmName("setExternalDocs")
      set(value) {
        _builder.setExternalDocs(value)
      }
    /**
     * <pre>
     * Additional external documentation for this tag.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 3;</code>
     */
    public fun clearExternalDocs() {
      _builder.clearExternalDocs()
    }
    /**
     * <pre>
     * Additional external documentation for this tag.
     * </pre>
     *
     * <code>.grpc.gateway.protoc_gen_openapiv2.options.ExternalDocumentation external_docs = 3;</code>
     * @return Whether the externalDocs field is set.
     */
    public fun hasExternalDocs(): kotlin.Boolean {
      return _builder.hasExternalDocs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag.copy(block: grpc.gateway.protoc_gen_openapiv2.options.TagKt.Dsl.() -> kotlin.Unit): grpc.gateway.protoc_gen_openapiv2.options.Openapiv2.Tag =
  grpc.gateway.protoc_gen_openapiv2.options.TagKt.Dsl._create(this.toBuilder()).apply { block() }._build()
